# -*- coding: utf-8 -*-
"""Part1_Payments_Fraud_Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtdnB09PlTai9CQLX2PeBtgjQLI1yFZa
"""

import random
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

random.seed(42)
np.random.seed(42)

CATEGORIES = ["grocery", "food_delivery", "recharge", "bill_payment", "travel",
              "ecommerce", "entertainment"]
REGIONS = ["North", "South", "East", "West"]
METHODS = ["UPI", "Wallet", "Card", "Netbanking"]
METHOD_WEIGHTS = [0.55, 0.20, 0.15, 0.10]
AMOUNTS_INR = [49, 99, 149, 299, 499, 799, 1499, 2999, 4999]
AMOUNT_WEIGHTS = [0.18, 0.16, 0.14, 0.14, 0.12, 0.10, 0.08, 0.05, 0.03]

# --- 40 merchants ---
merchants = pd.DataFrame({
    "merchant_id": range(1, 41),
    "merchant_name": [f"Merchant_{i:03d}" for i in range(1, 41)],
    "category": [random.choice(CATEGORIES) for _ in range(40)],
    "region": [random.choice(REGIONS) for _ in range(40)],
})

# --- 350 established users, signed up 30-730 days before the window start ---
window_start = datetime(2026, 1, 1)
users = pd.DataFrame({
    "user_id": range(1, 351),
    "signup_date": [window_start - timedelta(days=random.randint(30, 730)) for _ in range(350)],
})

# --- 500 baseline transactions over a 30-day window ---
rows = []
for i in range(500):
    txn_time = window_start + timedelta(
        days=random.randint(0, 29), hours=random.randint(0, 23), minutes=random.randint(0, 59))
    status = np.random.choice(["captured", "failed", "chargeback"], p=[0.92, 0.06, 0.02])
    rows.append({
        "transaction_id": f"TXN{100000+i}",
        "user_id": random.randint(1, 350),
        "merchant_id": random.randint(1, 40),
        "transaction_time": txn_time,
        "amount_inr": np.random.choice(AMOUNTS_INR, p=AMOUNT_WEIGHTS),
        "payment_method": np.random.choice(METHODS, p=METHOD_WEIGHTS),
        "status": status,
        "risk_score": random.randint(0, 100),
    })

# --- inject 15 "burner account" chargeback frauds: brand-new users (< 30 days old) ---
next_user_id = 351
for i in range(15):
    txn_time = window_start + timedelta(days=random.randint(10, 29), hours=random.randint(0, 23))
    signup = txn_time - timedelta(days=random.randint(1, 25))
    users = pd.concat([users, pd.DataFrame([{"user_id": next_user_id, "signup_date": signup}])],
                       ignore_index=True)
    rows.append({
        "transaction_id": f"TXN{200000+i}",
        "user_id": next_user_id,
        "merchant_id": random.randint(1, 40),
        "transaction_time": txn_time,
        "amount_inr": random.choice([999, 1999, 2999, 4999]),
        "payment_method": "Card",
        "status": "chargeback",
        "risk_score": random.randint(70, 100),
    })
    next_user_id += 1

# --- inject 8 velocity-attack clusters: 4 rapid-fire txns each within a 5-minute window ---
for cluster in range(8):
    victim_user = random.randint(1, 350)
    base_time = window_start + timedelta(days=random.randint(0, 29), hours=random.randint(0, 23))
    for k in range(4):
        rows.append({
            "transaction_id": f"TXN{300000 + cluster*4 + k}",
            "user_id": victim_user,
            "merchant_id": random.randint(1, 40),
            "transaction_time": base_time + timedelta(minutes=k),
            "amount_inr": random.choice([299, 399, 499]),
            "payment_method": "Card",
            "status": "captured" if k == 3 else "failed",
            "risk_score": random.randint(60, 95),
        })

ledger = pd.DataFrame(rows)  # 500 + 15 + 32 = 547 rows
merchants.to_csv("merchants.csv", index=False)
users.to_csv("users.csv", index=False)
ledger.to_csv("ledger.csv", index=False)

# --- build the deliberately-discrepant "gateway export" copy for reconciliation ---
gateway = ledger.copy()
n = len(gateway)
missing_idx = np.random.choice(n, size=int(0.05 * n), replace=False)
gateway = gateway.drop(index=missing_idx).reset_index(drop=True)

mismatch_idx = np.random.choice(len(gateway), size=int(0.03 * n), replace=False)
gateway.loc[mismatch_idx, "amount_inr"] = gateway.loc[mismatch_idx, "amount_inr"] + \
    np.random.choice([-100, -50, 50, 100], size=len(mismatch_idx))

extra_rows = []
for i in range(int(0.02 * n)):
    extra_rows.append({
        "transaction_id": f"TXNX{9000+i}", "user_id": random.randint(1, 350),
        "merchant_id": random.randint(1, 40),
        "transaction_time": window_start + timedelta(days=random.randint(0, 29)),
        "amount_inr": random.choice(AMOUNTS_INR),
        "payment_method": random.choice(METHODS),
        "status": "captured",
        "risk_score": random.randint(0, 100),
    })
gateway = pd.concat([gateway, pd.DataFrame(extra_rows)], ignore_index=True)

status_idx = np.random.choice(len(gateway), size=int(0.02 * n), replace=False)
gateway.loc[status_idx, "status"] = "failed"

gateway.to_csv("gateway_export.csv", index=False)

def sql_escape(value):
    return str(value).replace("'", "''")


def dataframe_to_sql(df, table_name):
    statements = []

    for _, row in df.iterrows():

        values = []

        for value in row:

            if pd.isna(value):
                values.append("NULL")

            elif isinstance(value, (int, float, np.integer, np.floating)):
                values.append(str(value))

            else:
                values.append(
                    "'" + sql_escape(value) + "'")

        statement = (
            f"INSERT INTO {table_name} VALUES "
            f"({', '.join(values)});")

        statements.append(statement)

    return "\n".join(statements)

merchant_sql = dataframe_to_sql(merchants,"merchants")

print(merchant_sql[:3000])

user_sql = dataframe_to_sql(users,"users")

print(user_sql[:3000])

transaction_sql = dataframe_to_sql(ledger,"transactions")

print(transaction_sql[:3000])

all_insert_sql = (
    merchant_sql
    + "\n"
    + user_sql
    + "\n"
    + transaction_sql)

print(len(all_insert_sql))

with open("paytm_data.sql", "w", encoding="utf-8") as f:
    f.write(all_insert_sql)

print("paytm_data.sql created")

import pandas as pd

ledger_df = pd.read_csv("ledger.csv")
gateway_df = pd.read_csv("gateway_export.csv")

print("Ledger shape:", ledger_df.shape)
print("Gateway shape:", gateway_df.shape)

ledger_df.head()

gateway_df.head()

def reconcile_payments(ledger_df, gateway_df):

# 1. Get transaction IDs from both systems
    ledger_ids = set(ledger_df["transaction_id"])
    gateway_ids = set(gateway_df["transaction_id"])

# 2. Set operations
# Transactions present in ledger but not gateway
    missing_in_gateway_ids = ledger_ids - gateway_ids

# Transactions present in gateway but not ledger
    extra_in_gateway_ids = gateway_ids - ledger_ids

# 3. Convert the ID sets back into DataFrames
    missing_in_gateway = ledger_df[
        ledger_df["transaction_id"].isin(missing_in_gateway_ids)
    ].copy()

    extra_in_gateway = gateway_df[
        gateway_df["transaction_id"].isin(extra_in_gateway_ids)
    ].copy()

# 4. Compare transactions existing in BOTH systems
    common_transactions = pd.merge(
        ledger_df,
        gateway_df,
        on="transaction_id",
        how="inner",
        suffixes=("_ledger", "_gateway"))

# 5. Amount mismatches
    amount_mismatches = common_transactions[
        common_transactions["amount_inr_ledger"]
        != common_transactions["amount_inr_gateway"]
    ].copy()

    amount_mismatches["amount_difference"] = (
        amount_mismatches["amount_inr_gateway"]
        - amount_mismatches["amount_inr_ledger"])

# 6. Status mismatches
    status_mismatches = common_transactions[
        common_transactions["status_ledger"]
        != common_transactions["status_gateway"]
    ].copy()

# 7. Return the four required DataFrames
    return (
        missing_in_gateway,
        extra_in_gateway,
        amount_mismatches,
        status_mismatches)

(missing_in_gateway,
 extra_in_gateway,
 amount_mismatches,
 status_mismatches) = reconcile_payments(
    ledger_df,
    gateway_df)

print("RECONCILIATION RESULTS:")

print("Missing in gateway:",len(missing_in_gateway))

print("Extra in gateway:",len(extra_in_gateway))

print("Amount mismatches:",len(amount_mismatches))

print("Status mismatches:",len(status_mismatches))

missing_in_gateway.head(10)

extra_in_gateway.head(10)

amount_mismatches[
    ["transaction_id",
        "amount_inr_ledger",
        "amount_inr_gateway",
        "amount_difference"]
].head(10)

status_mismatches[
    ["transaction_id",
        "status_ledger",
        "status_gateway"]
].head(10)

pd.merge(
    ledger_df,
    gateway_df,
    on="transaction_id",
    how="inner")

print("Ledger transactions:", len(ledger_df))

print("Missing in gateway:",len(missing_in_gateway))

print("Extra in gateway:",len(extra_in_gateway))

print("Common transactions:",
    len(set(ledger_df["transaction_id"])
        & set(gateway_df["transaction_id"])))

missing_in_gateway.to_csv("missing_in_gateway.csv",index=False)

extra_in_gateway.to_csv("extra_in_gateway.csv", index=False)

amount_mismatches.to_csv("amount_mismatches.csv",index=False)

status_mismatches.to_csv("status_mismatches.csv",index=False)

print("Four reconciliation reports saved.")

reconciliation_summary = pd.DataFrame({
    "discrepancy_type": [
        "Missing in gateway",
        "Extra in gateway",
        "Amount mismatch",
        "Status mismatch"    ],
    "count": [
        len(missing_in_gateway),
        len(extra_in_gateway),
        len(amount_mismatches),
        len(status_mismatches)]})

reconciliation_summary

reconciliation_summary["percentage_of_ledger"] = (
    reconciliation_summary["count"]
    / len(ledger_df)
    * 100)

reconciliation_summary

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ledger_df = pd.read_csv("ledger.csv")
gateway_df = pd.read_csv("gateway_export.csv")
merchants_df = pd.read_csv("merchants.csv")

ledger_df["transaction_time"] = pd.to_datetime(
    ledger_df["transaction_time"])

gateway_df["transaction_time"] = pd.to_datetime(
    gateway_df["transaction_time"])

print("Ledger:", ledger_df.shape)
print("Gateway:", gateway_df.shape)
print("Merchants:", merchants_df.shape)

dashboard_df = ledger_df.merge(
    merchants_df,
    on="merchant_id",
    how="left")

dashboard_df.head()

import os

os.makedirs("dashboard", exist_ok=True)

print("Dashboard folder created.")

total_gmv = ledger_df["amount_inr"].sum()

print("Total GMV: ₹", total_gmv)

success_rate = (
    (ledger_df["status"] == "captured").sum()
    / len(ledger_df)
    * 100)

print("Success rate:", round(success_rate, 2), "%")

success_rate = (
    (ledger_df["status"] == "captured").sum()
    / len(ledger_df)
    * 100)

print("Success rate:", round(success_rate, 2), "%")

comparison = pd.merge(
    ledger_df[
        ["transaction_id", "amount_inr", "status"]],
    gateway_df[
        ["transaction_id", "amount_inr", "status"]],
    on="transaction_id",
    how="inner",
    suffixes=("_ledger", "_gateway"))

matched_count = (
    (comparison["amount_inr_ledger"]
     == comparison["amount_inr_gateway"])
    &
    (comparison["status_ledger"]
     == comparison["status_gateway"])
).sum()

match_rate = (
    matched_count
    / len(ledger_df)
    * 100)

print("Matched transactions:", matched_count)
print("Match rate:", round(match_rate, 2), "%")

comparison = pd.merge(
    ledger_df[
        ["transaction_id", "amount_inr", "status"]],
    gateway_df[
        ["transaction_id", "amount_inr", "status"]],
    on="transaction_id",
    how="inner",
    suffixes=("_ledger", "_gateway"))

matched_count = (
    (comparison["amount_inr_ledger"]
     == comparison["amount_inr_gateway"])
    &
    (comparison["status_ledger"]
     == comparison["status_gateway"])
).sum()

match_rate = (
    matched_count
    / len(ledger_df)
    * 100)

print("Matched transactions:", matched_count)
print("Match rate:", round(match_rate, 2), "%")

chargeback_count = (
    ledger_df["status"] == "chargeback"
).sum()

chargeback_ratio = (
    chargeback_count
    / len(ledger_df)
    * 100)

print("Chargeback transactions:", chargeback_count)
print("Chargeback ratio:", round(chargeback_ratio, 2), "%")

print("HEADLINE METRICS")
print(f"Total GMV: ₹{total_gmv:,.2f}")
print(f"Success Rate: {success_rate:.2f}%")
print(f"Reconciliation Match Rate: {match_rate:.2f}%")
print(f"Chargeback Ratio: {chargeback_ratio:.2f}%")

fig, ax = plt.subplots(figsize=(12, 5))

ax.axis("off")

metrics = [
    ("TOTAL GMV", f"₹{total_gmv:,.0f}"),
    ("SUCCESS RATE", f"{success_rate:.2f}%"),
    ("MATCH RATE", f"{match_rate:.2f}%"),
    ("CHARGEBACK RATIO", f"{chargeback_ratio:.2f}%")]

for i, (label, value) in enumerate(metrics):
    x = (i + 0.5) / len(metrics)

    ax.text(
        x,
        0.65,
        value,
        ha="center",
        va="center",
        fontsize=24,
        fontweight="bold",
        transform=ax.transAxes)

    ax.text(
        x,
        0.30,
        label,
        ha="center",
        va="center",
        fontsize=11,
        transform=ax.transAxes)

ax.set_title(
    "Paytm Payments & Fraud Analytics — Headline Metrics",
    fontsize=16,
    fontweight="bold",
    pad=20)

plt.tight_layout()

plt.savefig(
    "dashboard/01_headline.png",
    dpi=200,
    bbox_inches="tight")

plt.show()

"""### Headline Interpretation

The platform processed ₹382,603 in GMV with an 85.56% transaction success rate. The 90.49% reconciliation match rate shows that most transactions agree between the ledger and gateway, while the 5.12% chargeback ratio indicates a fraud signal that should be monitored.
"""

ledger_df["transaction_date"] = (
    ledger_df["transaction_time"].dt.date)

daily_gmv = (
    ledger_df
    .groupby("transaction_date")["amount_inr"]
    .sum())

daily_chargebacks = (
    ledger_df[
        ledger_df["status"] == "chargeback"
    ]
    .groupby("transaction_date")
    .size())

trend_df = pd.DataFrame({
    "daily_gmv": daily_gmv,
    "daily_chargebacks": daily_chargebacks
}).fillna(0)

fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.plot(
    trend_df.index,
    trend_df["daily_gmv"],
    marker="o",
    label="Daily GMV")

ax1.set_xlabel("Date")
ax1.set_ylabel("Daily GMV (INR)")

ax2 = ax1.twinx()

ax2.plot(
    trend_df.index,
    trend_df["daily_chargebacks"],
    marker="s",
    label="Daily Chargebacks")

ax2.set_ylabel("Daily Chargeback Count")

ax1.set_title(
    "Daily GMV and Chargeback Trend",
    fontsize=16,
    fontweight="bold")

fig.autofmt_xdate()

plt.tight_layout()

plt.savefig(
    "dashboard/02_trends.png",
    dpi=200,
    bbox_inches="tight")

plt.show()

"""### Trends Interpretation

Daily GMV fluctuates across the 30-day period without a clear weekly pattern. Some higher-volume days also show increases in chargeback activity, suggesting that transaction volume and fraud exposure should be monitored together.
"""

gmv_by_method = (
    dashboard_df
    .groupby("payment_method")["amount_inr"]
    .sum()
    .sort_values(ascending=False))

gmv_by_method

gmv_by_category = (
    dashboard_df
    .groupby("category")["amount_inr"]
    .sum()
    .sort_values(ascending=False))

gmv_by_category

fig, ax = plt.subplots(figsize=(12, 7))

x = np.arange(len(gmv_by_method))
width = 0.35

method_values = gmv_by_method.values

category_values = np.array([
        gmv_by_category.get(category, 0)
        for category in gmv_by_category.index])

# We'll use two separate panels vertically in the final image
plt.close()

fig, axes = plt.subplots(2,1,
    figsize=(12, 10))

# Payment method
axes[0].bar(
    gmv_by_method.index,
    gmv_by_method.values)

axes[0].set_title(
    "GMV by Payment Method",
    fontweight="bold")

axes[0].set_ylabel("GMV (INR)")


# Category
axes[1].bar(
    gmv_by_category.index,
    gmv_by_category.values)

axes[1].set_title(
    "GMV by Merchant Category",
    fontweight="bold")

axes[1].set_ylabel("GMV (INR)")

axes[1].tick_params(axis="x", rotation=30)

fig.suptitle(
    "Payment & Merchant Category Breakdown",
    fontsize=16,
    fontweight="bold")

plt.tight_layout()

plt.savefig(
    "dashboard/03_breakdown.png",
    dpi=200,
    bbox_inches="tight")

plt.show()

"""### Breakdown Interpretation

UPI contributes the largest share of GMV among the payment methods, consistent with its higher transaction-generation weight in the synthetic dataset. The category breakdown shows how transaction value is distributed across the different merchant categories.
"""

merchant_stats = (
    dashboard_df
    .groupby([
            "merchant_id",
            "merchant_name"])
    .agg(
        transaction_count=(
            "transaction_id",
            "count"),
        chargeback_count=(
            "status",
            lambda x: (x == "chargeback").sum()),
        total_gmv=(
            "amount_inr",
            "sum"))
    .reset_index())

merchant_stats["chargeback_ratio"] = (
    merchant_stats["chargeback_count"]
    / merchant_stats["transaction_count"]
    * 100)

merchant_stats["risk_flag"] = np.where(
    merchant_stats["chargeback_ratio"] > 1,
    "HIGH RISK",
    "Normal")

top10_merchants = (
    merchant_stats
    .sort_values(
        "transaction_count",
        ascending=False)
    .head(10)
    .copy())

top10_merchants

top10_merchants[[
        "merchant_id",
        "merchant_name",
        "transaction_count",
        "chargeback_count",
        "chargeback_ratio",
        "risk_flag"]]

display_df = top10_merchants[[
        "merchant_id",
        "merchant_name",
        "transaction_count",
        "chargeback_count",
        "chargeback_ratio",
        "risk_flag"]
].copy()

display_df["chargeback_ratio"] = (
    display_df["chargeback_ratio"]
    .round(2)
    .astype(str)
    + "%")

fig, ax = plt.subplots(
    figsize=(13, 6))

ax.axis("off")

table = ax.table(
    cellText=display_df.values,
    colLabels=display_df.columns,
    cellLoc="center",
    loc="center")

table.auto_set_font_size(False)
table.set_fontsize(9)
table.scale(1, 1.8)

ax.set_title(
    "Top 10 Merchants by Transaction Count",
    fontsize=16,
    fontweight="bold",
    pad=20)

plt.tight_layout()

plt.savefig(
    "dashboard/04_details.png",
    dpi=200,
    bbox_inches="tight")

plt.show()

"""### Details Interpretation

Several of the highest-volume merchants exceed the 1% chargeback-ratio threshold and therefore require closer monitoring. Merchants with particularly high chargeback ratios should be prioritized for manual review even when their overall transaction volume is relatively high.
"""

print(top10_merchants[[
            "merchant_name",
            "chargeback_ratio",
            "risk_flag"]])

import sqlite3

# Create/connect to the SQLite database
conn = sqlite3.connect("paytm_payments.db")
cursor = conn.cursor()

# Enable foreign key constraints
cursor.execute("PRAGMA foreign_keys = ON;")

# Create the three tables
cursor.executescript("""
CREATE TABLE IF NOT EXISTS merchants (
    merchant_id INTEGER PRIMARY KEY,
    merchant_name TEXT,
    category TEXT,
    region TEXT
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY,
    signup_date TEXT
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id TEXT PRIMARY KEY,
    user_id INTEGER,
    merchant_id INTEGER,
    transaction_time TEXT,
    amount_inr REAL,
    payment_method TEXT,
    status TEXT,
    risk_score INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (merchant_id) REFERENCES merchants(merchant_id)
);
""")

print("Database and tables created successfully.")

import pandas as pd

# Load the CSV files
merchants_df = pd.read_csv("merchants.csv")
users_df = pd.read_csv("users.csv")
transactions_df = pd.read_csv("ledger.csv")

# Insert the data into the SQLite tables
merchants_df.to_sql("merchants", conn, if_exists="append", index=False)
users_df.to_sql("users", conn, if_exists="append", index=False)
transactions_df.to_sql("transactions", conn, if_exists="append", index=False)

print("All CSV data loaded into the database successfully.")

# Check the number of rows in each table

print("Merchants:", pd.read_sql("SELECT COUNT(*) AS count FROM merchants", conn)["count"][0])
print("Users:", pd.read_sql("SELECT COUNT(*) AS count FROM users", conn)["count"][0])
print("Transactions:", pd.read_sql("SELECT COUNT(*) AS count FROM transactions", conn)["count"][0])

# Query 1: Basic SELECT + LIMIT

query1 = """
SELECT *
FROM transactions
LIMIT 10;
"""

result1 = pd.read_sql_query(query1, conn)
result1

query = """
SELECT
    transaction_id,
    user_id,
    amount_inr,
    status
FROM transactions
WHERE status = 'chargeback'
ORDER BY amount_inr DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

query_payment_method = """
SELECT DISTINCT payment_method
FROM transactions;
"""

pd.read_sql_query(query_payment_method, conn)

query_merchant_counts = """
SELECT
    merchant_id,
    COUNT(*) AS transaction_count
FROM transactions
GROUP BY merchant_id
HAVING COUNT(*) > 10
ORDER BY transaction_count DESC;
"""

result_merchant_counts = pd.read_sql_query(query_merchant_counts, conn)
result_merchant_counts

query_chargeback_summary = """
SELECT
    COUNT(*) AS chargeback_count,
    COUNT(DISTINCT user_id) AS unique_users_affected,
    SUM(amount_inr) AS total_chargeback_amount
FROM transactions
WHERE status = 'chargeback';
"""

chargeback_summary = pd.read_sql_query(query_chargeback_summary, conn)
chargeback_summary

query_transactions_users = """
SELECT
    t.transaction_id,
    t.user_id,
    u.signup_date,
    t.amount_inr,
    t.status
FROM transactions t
INNER JOIN users u
    ON t.user_id = u.user_id
LIMIT 10;
"""

result_transactions_users = pd.read_sql_query(query_transactions_users, conn)
result_transactions_users

query_transactions_merchants = """
SELECT
    t.transaction_id,
    t.merchant_id,
    m.merchant_name,
    m.category,
    m.region
FROM transactions t
LEFT JOIN merchants m
    ON t.merchant_id = m.merchant_id
LIMIT 10;
"""

result_transactions_merchants = pd.read_sql_query(query_transactions_merchants, conn)
result_transactions_merchants

query_fraud_early_transactions = """
SELECT
    t.transaction_id,
    t.user_id,
    u.signup_date,
    t.transaction_time,
    t.amount_inr,
    t.status,
    ROUND(
        julianday(t.transaction_time)
        - julianday(u.signup_date),
        2
    ) AS account_age_days
FROM transactions t
INNER JOIN users u
    ON t.user_id = u.user_id
WHERE t.status = 'chargeback'
  AND julianday(t.transaction_time) >= julianday(u.signup_date)
  AND julianday(t.transaction_time)
      - julianday(u.signup_date) < 30
ORDER BY account_age_days;
"""

result_fraud_early_transactions = pd.read_sql_query(query_fraud_early_transactions, conn)
result_fraud_early_transactions

query_ten_minute_bucket = """
SELECT
    user_id,
    datetime(
        (CAST(strftime('%s', transaction_time) AS INTEGER) / 600) * 600,
        'unixepoch'
    ) AS ten_minute_bucket,
    COUNT(*) AS transaction_count
FROM transactions
GROUP BY
    user_id,
    ten_minute_bucket
HAVING COUNT(*) >= 3
ORDER BY transaction_count DESC;
"""

result_ten_minute_bucket = pd.read_sql_query(query_ten_minute_bucket, conn)
result_ten_minute_bucket