# -*- coding: utf-8 -*-
"""Part2_Credit_Risk_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bydQxicwDe9stLGNYT-mLTb6e-D6GPuJ
"""

import numpy as np
import pandas as pd

np.random.seed(42)
N = 400

age = np.random.randint(21, 60, N)
monthly_income_inr = np.random.randint(15000, 150000, N)
existing_loans_count = np.random.randint(0, 5, N)
credit_utilization_ratio = np.round(np.random.uniform(0.05, 0.95, N), 2)
upi_monthly_inflow_inr = np.random.randint(2000, 120000, N)
bounced_payments_count = np.random.poisson(1.2, N)
employment_type = np.random.choice(["salaried", "self_employed", "gig"], N,
                                    p=[0.55, 0.30, 0.15])
credit_bureau_score = np.random.randint(300, 900, N).astype(float)

# 20% of applicants are "new to credit" (thin-file): no bureau score at all
thin_file_idx = np.random.choice(N, size=int(0.20 * N), replace=False)
credit_bureau_score[thin_file_idx] = np.nan

# risk score combines income (protective), bounced payments and utilization (risky),
# and UPI inflow (protective, alternate-data signal) -- deliberately usable even
# when credit_bureau_score is missing
z_income = (monthly_income_inr - monthly_income_inr.mean()) / monthly_income_inr.std()
z_bounced = (bounced_payments_count - bounced_payments_count.mean()) / (bounced_payments_count.std() + 1e-9)
z_util = (credit_utilization_ratio - credit_utilization_ratio.mean()) / credit_utilization_ratio.std()
z_upi = (upi_monthly_inflow_inr - upi_monthly_inflow_inr.mean()) / upi_monthly_inflow_inr.std()

risk_score = -2.25 + (-0.9 * z_income) + (0.8 * z_bounced) + (0.7 * z_util) + (-0.5 * z_upi) \
    + np.random.normal(0, 0.6, N)
default_prob = 1 / (1 + np.exp(-risk_score))
default = (np.random.uniform(0, 1, N) < default_prob).astype(int)

df = pd.DataFrame({
    "applicant_id": [f"APP{1000+i}" for i in range(N)],
    "age": age,
    "monthly_income_inr": monthly_income_inr,
    "existing_loans_count": existing_loans_count,
    "credit_utilization_ratio": credit_utilization_ratio,
    "upi_monthly_inflow_inr": upi_monthly_inflow_inr,
    "bounced_payments_count": bounced_payments_count,
    "credit_bureau_score": credit_bureau_score,
    "employment_type": employment_type,
    "default": default,
})
df.to_csv("credit_applicants.csv", index=False)
print(df["default"].value_counts(normalize=True))

# --- second dataset: transaction-behaviour rows for anomaly detection ---
M = 250
behaviour = pd.DataFrame({
    "txn_id": [f"BTXN{5000+i}" for i in range(M)],
    "applicant_id": np.random.choice(df["applicant_id"], M),
    "txn_hour": np.random.randint(6, 23, M),
    "is_new_device": np.random.choice([0, 1], M, p=[0.9, 0.1]),
    "txn_amount_inr": np.random.choice([199, 499, 999, 1999, 3999], M,
                                        p=[0.30, 0.28, 0.22, 0.13, 0.07]),
    "channel": np.random.choice(["P2P", "P2M"], M, p=[0.4, 0.6]),
})
# inject 15 deliberate anomalies: new device, unusual hour (1-4am), high amount
anomalies = pd.DataFrame({
    "txn_id": [f"BTXNA{i}" for i in range(15)],
    "applicant_id": np.random.choice(df["applicant_id"], 15),
    "txn_hour": np.random.randint(1, 5, 15),
    "is_new_device": 1,
    "txn_amount_inr": np.random.choice([14999, 19999, 24999], 15),
    "channel": "P2P",
})
behaviour = pd.concat([behaviour, anomalies], ignore_index=True)  # 265 rows total
behaviour.to_csv("txn_behaviour.csv", index=False)

import pandas as pd
import numpy as np

df = pd.read_csv("credit_applicants.csv")

print("Dataset loaded successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

df.info()

missing_values = df.isnull().sum()

print(missing_values)

missing_bureau_count = df["credit_bureau_score"].isna().sum()

missing_bureau_percentage = (missing_bureau_count
    / len(df)
    * 100)

print("Missing bureau scores:", missing_bureau_count)

print("Missing bureau score percentage:",round(missing_bureau_percentage, 2),"%")

default_rate = df["default"].mean() * 100

print("Default rate:",round(default_rate, 2),"%")

df["default"].value_counts()

df["default"].value_counts(normalize=True) * 100

df["is_thin_file"] = (
    df["credit_bureau_score"].isna()
).astype(int)

df["is_thin_file"].value_counts()

pd.crosstab(
    df["is_thin_file"],
    df["credit_bureau_score"].isna())

df.describe()

df["employment_type"].value_counts()

pd.crosstab(
    df["employment_type"],
    df["is_thin_file"])

df.groupby("is_thin_file")["default"].mean() * 100

df.groupby("default")[
    "monthly_income_inr"
].mean()

df.groupby("default")[
    "credit_utilization_ratio"
].mean()

df.groupby("default")[
    "bounced_payments_count"
].mean()

eda_summary = pd.DataFrame({
    "Metric": [
        "Total applicants",
        "Default rate",
        "Missing bureau scores",
        "Missing bureau percentage",
        "Thin-file applicants"],
    "Value": [
        len(df),
        f"{default_rate:.2f}%",
        missing_bureau_count,
        f"{missing_bureau_percentage:.2f}%",
        df["is_thin_file"].sum()]})
eda_summary

df.to_csv(
    "credit_applicants_eda.csv",
    index=False)

print("EDA dataset saved.")

from sklearn.model_selection import train_test_split

X = df.drop(columns=["default"])
y = df["default"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    stratify=y,
    random_state=42)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

print("Overall default rate:")
print(y.mean())

print("\nTraining default rate:")
print(y_train.mean())

print("\nTesting default rate:")
print(y_test.mean())

bureau_median = X_train[
    "credit_bureau_score"
].median()

print("Training-only bureau score median:",bureau_median)

print("Missing bureau scores in training:", X_train["credit_bureau_score"].isna().sum())

print("Missing bureau scores in testing:", X_test["credit_bureau_score"].isna().sum())

X_train["credit_bureau_score"] = (
    X_train["credit_bureau_score"]
    .fillna(bureau_median))

X_test["credit_bureau_score"] = (
    X_test["credit_bureau_score"]
    .fillna(bureau_median))

print("Missing bureau scores after imputation:")

print("Training:", X_train["credit_bureau_score"].isna().sum())

print("Testing:",X_test["credit_bureau_score"].isna().sum())

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

print(X_train["is_thin_file"].value_counts())

print()

print(X_test["is_thin_file"].value_counts())

print("PREPROCESSING CHECK")

print("Total applicants:", len(df))
print("Training applicants:", len(X_train))
print("Testing applicants:", len(X_test))

print("Training missing bureau scores:",X_train["credit_bureau_score"].isna().sum())

print("Testing missing bureau scores:",X_test["credit_bureau_score"].isna().sum())

print("Training thin-file applicants:",X_train["is_thin_file"].sum())

print("Testing thin-file applicants:",X_test["is_thin_file"].sum())

print("Training median used:",bureau_median)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

numeric_features = [
    "age",
    "monthly_income_inr",
    "existing_loans_count",
    "credit_utilization_ratio",
    "upi_monthly_inflow_inr",
    "bounced_payments_count",
    "credit_bureau_score",
    "is_thin_file"]

categorical_features = ["employment_type"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num",
            StandardScaler(),
            numeric_features),
        ("cat",
            OneHotEncoder(
                handle_unknown="ignore"),
            categorical_features)])

handle_unknown="ignore"

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)
print("Original test shape:", X_test.shape)
print("Processed test shape:", X_test_processed.shape)

feature_names = (preprocessor.get_feature_names_out())

print(feature_names)

# X_train = X_train.drop(columns=["applicant_id"])

# X_test = X_test.drop(columns=["applicant_id"])

print(X_train.columns.tolist())

numeric_features = [
    "age",
    "monthly_income_inr",
    "existing_loans_count",
    "credit_utilization_ratio",
    "upi_monthly_inflow_inr",
    "bounced_payments_count",
    "credit_bureau_score",
    "is_thin_file"]

categorical_features = ["employment_type"]

preprocessor = ColumnTransformer(
    transformers=[(
            "num",
            StandardScaler(),
            numeric_features),(
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"),
            categorical_features)])

X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training processed shape:", X_train_processed.shape)
print("Testing processed shape:", X_test_processed.shape)

print("Training feature count:",
    len(preprocessor.get_feature_names_out()))

print("Training-only bureau median:", bureau_median)

print("Remaining training missing values:", X_train["credit_bureau_score"].isna().sum())

print("Remaining testing missing values:", X_test["credit_bureau_score"].isna().sum())

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42)

logistic_model.fit(
    X_train_processed,
    y_train)

y_pred_logistic = logistic_model.predict(
    X_test_processed)

y_prob_logistic = logistic_model.predict_proba(
    X_test_processed
)[:, 1]

print("First 10 predicted classes:")
print(y_pred_logistic[:10])

print("\nFirst 10 default probabilities:")
print(np.round(y_prob_logistic[:10],3))

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report)

accuracy_logistic = accuracy_score(
    y_test,
    y_pred_logistic)

print("Accuracy:",round(accuracy_logistic, 4))

precision_logistic = precision_score(
    y_test,
    y_pred_logistic,
    zero_division=0)

print("Precision:",round(precision_logistic, 4))

recall_logistic = recall_score(
    y_test,
    y_pred_logistic,
    zero_division=0)

print("Recall:",round(recall_logistic, 4))

f1_logistic = f1_score(
    y_test,
    y_pred_logistic,
    zero_division=0)

print("F1-score:",round(f1_logistic, 4))

roc_auc_logistic = roc_auc_score(
    y_test,
    y_prob_logistic)

print("ROC-AUC:",round(roc_auc_logistic, 4))

cm_logistic = confusion_matrix(
    y_test,
    y_pred_logistic)

print(cm_logistic)

print(
    classification_report(
        y_test,
        y_pred_logistic,
        zero_division=0))

logistic_results = pd.DataFrame({
    "Model": ["Logistic Regression"],
    "Accuracy": [accuracy_logistic],
    "Precision": [precision_logistic],
    "Recall": [recall_logistic],
    "F1": [f1_logistic],
    "ROC_AUC": [roc_auc_logistic]})

logistic_results

logistic_predictions = pd.DataFrame({
    "actual_default": y_test.values,
    "predicted_default": y_pred_logistic,
    "default_probability": y_prob_logistic})

logistic_predictions.head(10)

from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=42)

decision_tree.fit(
    X_train_processed,
    y_train)

y_pred_tree = decision_tree.predict(
    X_test_processed)

y_prob_tree = decision_tree.predict_proba(
    X_test_processed
)[:, 1]

accuracy_tree = accuracy_score(
    y_test,
    y_pred_tree)

print("Decision Tree Accuracy:",round(accuracy_tree, 4))

precision_tree = precision_score(
    y_test,
    y_pred_tree,
    zero_division=0)

print("Decision Tree Precision:",round(precision_tree, 4))

recall_tree = recall_score(
    y_test,
    y_pred_tree,
    zero_division=0)

print("Decision Tree Recall:",round(recall_tree, 4))

f1_tree = f1_score(
    y_test,
    y_pred_tree,
    zero_division=0)

print("Decision Tree F1:",round(f1_tree, 4))

roc_auc_tree = roc_auc_score(
    y_test,
    y_prob_tree)

print("Decision Tree ROC-AUC:",round(roc_auc_tree, 4))

cm_tree = confusion_matrix(
    y_test,
    y_pred_tree)

print(cm_tree)

print(
    classification_report(
        y_test,
        y_pred_tree,
        zero_division=0))

tree_results = pd.DataFrame({
    "Model": ["Decision Tree"],
    "Accuracy": [accuracy_tree],
    "Precision": [precision_tree],
    "Recall": [recall_tree],
    "F1": [f1_tree],
    "ROC_AUC": [roc_auc_tree]})

tree_results

model_comparison = pd.concat([
        logistic_results,
        tree_results],
    ignore_index=True)

model_comparison

import matplotlib.pyplot as plt

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "ROC_AUC"]

comparison_plot = model_comparison.set_index("Model")[metrics]

comparison_plot.plot(
    kind="bar",
    figsize=(10, 6))

plt.title("Credit Risk Model Comparison")

plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.legend(title="Metric")

plt.tight_layout()
plt.show()

model_comparison.to_csv(
    "model_comparison.csv",
    index=False)

print("Model comparison saved.")

model_predictions = pd.DataFrame({
    "actual_default": y_test.values,
    "logistic_probability": y_prob_logistic,
    "logistic_prediction": y_pred_logistic,
    "tree_probability": y_prob_tree,
    "tree_prediction": y_pred_tree})

model_predictions.head()

print(model_comparison.to_string(index=False))

selected_model = logistic_model
selected_probabilities = y_prob_logistic

print("First 10 predicted default probabilities:")
print(np.round(y_prob_logistic[:10], 4))

pricing_df = pd.DataFrame({
    "applicant_id": df.loc[
        X_test.index,
        "applicant_id"
    ].values,

    "actual_default": y_test.values,

    "predicted_default_probability": y_prob_logistic})

pricing_df.head()

pricing_df["default_probability_pct"] = (
    pricing_df["predicted_default_probability"]
    * 100)

pricing_df.head()

pricing_df["risk_tier"] = pd.cut(
    pricing_df["predicted_default_probability"],
    bins=[
        -np.inf,
        0.10,
        0.20,
        0.30,
        np.inf],
    labels=[
        "Low",
        "Moderate",
        "High",
        "Very High"])

pricing_df[
    ["predicted_default_probability",
        "risk_tier"]].head(10)

pricing_df["risk_tier"].value_counts(sort=False)

base_rate = 0.07
risk_premium_factor = 0.12
maximum_rate = 0.18

pricing_df["risk_premium"] = (risk_premium_factor* pricing_df["predicted_default_probability"])

pricing_df["final_interest_rate"] = (
    base_rate
    + pricing_df["risk_premium"])

pricing_df["final_interest_rate"] = (
    pricing_df["final_interest_rate"]
    .clip(upper=maximum_rate))

pricing_df["final_rate_pct"] = (
    pricing_df["final_interest_rate"]
    * 100)

pricing_df["risk_premium_pct"] = (
    pricing_df["risk_premium"]
    * 100)

pricing_df[
    ["applicant_id",
        "predicted_default_probability",
        "risk_tier",
        "risk_premium_pct",
        "final_rate_pct"]
].head(15)

pricing_df.iloc[0][
    ["predicted_default_probability",
        "risk_premium",
        "final_interest_rate"]]

print(
    "Maximum final interest rate:",
    pricing_df["final_interest_rate"].max() * 100,
    "%")

print(
    "Any rate above 18%?",
    (pricing_df["final_interest_rate"] > 0.18
    ).any())

tier_summary = (
    pricing_df
    .groupby("risk_tier", observed=False)
    .agg(
        applicants=("applicant_id", "count"),
        avg_default_probability=(
            "predicted_default_probability",
            "mean"),
        avg_interest_rate=(
            "final_interest_rate",
            "mean"))
    .reset_index())

tier_summary["avg_default_probability"] = (
    tier_summary["avg_default_probability"] * 100)

tier_summary["avg_interest_rate"] = (
    tier_summary["avg_interest_rate"] * 100)

tier_summary

pricing_summary = tier_summary.copy()

pricing_summary[
    "avg_default_probability"
] = pricing_summary[
    "avg_default_probability"
].round(2)

pricing_summary[
    "avg_interest_rate"
] = pricing_summary[
    "avg_interest_rate"
].round(2)

pricing_summary

tier_summary["actual_default_rate"] = (
    pricing_df.groupby("risk_tier")["actual_default"].mean().values
)

pricing_df.to_csv("risk_based_pricing.csv",index=False)

tier_summary.to_csv("risk_tier_summary.csv",index=False)

print("Pricing files saved.")

print("\nRisk Tier Summary:")
print(tier_summary.to_string(index=False))

behaviour = pd.read_csv("txn_behaviour.csv")

print("Rows:", len(behaviour))
print("Columns:", len(behaviour.columns))

behaviour.head()

behaviour.columns.tolist()

behaviour["actual_anomaly"] = (
    behaviour["txn_id"].str.startswith("BTXNA")
).astype(int)

behaviour["actual_anomaly"].value_counts()

behaviour[
    behaviour["actual_anomaly"] == 0
].head(10)

behaviour[
    behaviour["actual_anomaly"] == 1
].head(10)

anomaly_features = [
    "txn_hour",
    "is_new_device",
    "txn_amount_inr"]

X_anomaly = behaviour[
    anomaly_features
].copy()

X_anomaly.head()

from sklearn.ensemble import IsolationForest

contamination_rate = 15 / 265

print("Contamination rate:",contamination_rate)

isolation_forest = IsolationForest(
    n_estimators=200,
    contamination=contamination_rate,
    random_state=42)

X_anomaly_scaled = StandardScaler().fit_transform(X_anomaly)
isolation_forest.fit(X_anomaly_scaled)
anomaly_prediction = isolation_forest.predict(X_anomaly_scaled)

behaviour["predicted_anomaly"] = (
    anomaly_prediction == -1
).astype(int)

behaviour[
    "predicted_anomaly"
].value_counts()

detected_anomalies = behaviour[
    behaviour["predicted_anomaly"] == 1
].copy()

detected_anomalies[[
        "txn_id",
        "txn_hour",
        "is_new_device",
        "txn_amount_inr",
        "channel"]]

cm_anomaly = confusion_matrix(
    behaviour["actual_anomaly"],
    behaviour["predicted_anomaly"])

print(cm_anomaly)

anomaly_precision = precision_score(
    behaviour["actual_anomaly"],
    behaviour["predicted_anomaly"],
    zero_division=0)

print("Anomaly Precision:", round(anomaly_precision, 4))

anomaly_recall = recall_score(
    behaviour["actual_anomaly"],
    behaviour["predicted_anomaly"],
    zero_division=0)

print("Anomaly Recall:", round(anomaly_recall, 4))

anomaly_f1 = f1_score(
    behaviour["actual_anomaly"],
    behaviour["predicted_anomaly"],
    zero_division=0)

print("Anomaly F1:", round(anomaly_f1, 4))

true_positives = ((
        behaviour["actual_anomaly"] == 1) &(
        behaviour["predicted_anomaly"] == 1)
).sum()

print("Planted anomalies detected:", true_positives,"out of 15")

anomaly_summary = pd.DataFrame({
    "Metric": [
        "Total transactions",
        "Actual anomalies",
        "Detected anomalies",
        "Anomalies correctly detected",
        "Precision",
        "Recall",
        "F1"],
    "Value": [
        len(behaviour),
        behaviour["actual_anomaly"].sum(),
        behaviour["predicted_anomaly"].sum(),
        true_positives,
        anomaly_precision,
        anomaly_recall,
        anomaly_f1]})

anomaly_summary

false_positives = behaviour[
    (behaviour["actual_anomaly"] == 0)
    &
    (behaviour["predicted_anomaly"] == 1)]

false_positives[[
        "txn_id",
        "txn_hour",
        "is_new_device",
        "txn_amount_inr",
        "channel"]]

false_negatives = behaviour[
    (behaviour["actual_anomaly"] == 1)
    &
    (behaviour["predicted_anomaly"] == 0)]

false_negatives[[
        "txn_id",
        "txn_hour",
        "is_new_device",
        "txn_amount_inr",
        "channel"]]

behaviour["anomaly_score"] = (
    isolation_forest.decision_function(
        X_anomaly))

behaviour.sort_values(
    "anomaly_score"
).head(20)[[
        "txn_id",
        "txn_hour",
        "is_new_device",
        "txn_amount_inr",
        "channel",
        "anomaly_score",
        "actual_anomaly",
        "predicted_anomaly"]]

behaviour.to_csv(
    "anomaly_detection_results.csv",
    index=False)

anomaly_summary.to_csv(
    "anomaly_summary.csv",
    index=False)

print("Anomaly detection results saved.")

print("ANOMALY CHECK")

print("Total transactions:", len(behaviour))

print("Actual planted anomalies:", behaviour["actual_anomaly"].sum())

print("Detected anomalies:", behaviour["predicted_anomaly"].sum())

print("Correctly detected:", true_positives)

print("Recall:", round(anomaly_recall, 4))

print("Precision:",round(anomaly_precision, 4))

print("F1:", round(anomaly_f1, 4))

subgroup_analysis = X_test.copy()

subgroup_analysis["actual_default"] = y_test.values
subgroup_analysis["predicted_default"] = y_pred_logistic
subgroup_analysis["default_probability"] = y_prob_logistic

subgroup_analysis.head()

subgroup_analysis["is_thin_file"].value_counts()

subgroup_analysis["applicant_group"] = (
    subgroup_analysis["is_thin_file"]
    .map({
        0: "Non-Thin-File",
        1: "Thin-File"}))

subgroup_analysis[[
        "applicant_group",
        "is_thin_file",
        "actual_default",
        "predicted_default",
        "default_probability"]
].head()

subgroup_analysis[[
        "applicant_group",
        "is_thin_file",
        "actual_default",
        "predicted_default",
        "default_probability"]
].head()

group_counts = (
    subgroup_analysis
    .groupby("applicant_group")
    .size()
    .reset_index(name="applicants"))

group_counts

actual_default_rates = (
    subgroup_analysis
    .groupby("applicant_group")["actual_default"]
    .mean()
    .mul(100)
    .reset_index(name="actual_default_rate_pct"))

actual_default_rates

predicted_risk = (
    subgroup_analysis
    .groupby("applicant_group")[
        "default_probability"]
    .mean()
    .mul(100)
    .reset_index(
        name="average_predicted_default_probability_pct"))

predicted_risk

group_recall = []

for group in [
    "Non-Thin-File",
    "Thin-File"]:

    subset = subgroup_analysis[
        subgroup_analysis["applicant_group"] == group]

    recall = recall_score(
        subset["actual_default"],
        subset["predicted_default"],
        zero_division=0)

    group_recall.append({
        "Applicant Group": group,
        "Recall": recall})

group_recall = pd.DataFrame(group_recall)

group_recall

group_precision = []

for group in [
    "Non-Thin-File",
    "Thin-File"]:

    subset = subgroup_analysis[
        subgroup_analysis["applicant_group"] == group]

    precision = precision_score(
        subset["actual_default"],
        subset["predicted_default"],
        zero_division=0)

    group_precision.append({
        "Applicant Group": group,
        "Precision": precision})

group_precision = pd.DataFrame(group_precision)

group_precision

group_f1 = []

for group in [
    "Non-Thin-File",
    "Thin-File"]:

    subset = subgroup_analysis[
        subgroup_analysis["applicant_group"] == group]

    f1 = f1_score(
        subset["actual_default"],
        subset["predicted_default"],
        zero_division=0)

    group_f1.append({
        "Applicant Group": group,
        "F1": f1})

group_f1 = pd.DataFrame(group_f1)

group_f1

subgroup_summary = (
    subgroup_analysis
    .groupby("applicant_group")
    .agg(
        applicants=("actual_default", "count"),
        actual_default_rate=(
            "actual_default",
            "mean"),
        average_predicted_risk=(
            "default_probability",
            "mean"))
    .reset_index())

subgroup_summary

subgroup_metrics = []

for group in [
    "Non-Thin-File",
    "Thin-File"]:

    subset = subgroup_analysis[
        subgroup_analysis["applicant_group"] == group]

    subgroup_metrics.append({
        "applicant_group": group,
        "applicants": len(subset),
        "actual_default_rate": subset[
            "actual_default"
        ].mean(),
        "average_predicted_risk": subset[
            "default_probability"
        ].mean(),
        "precision": precision_score(
            subset["actual_default"],
            subset["predicted_default"],
            zero_division=0),
        "recall": recall_score(
            subset["actual_default"],
            subset["predicted_default"],
            zero_division=0),
        "f1": f1_score(
            subset["actual_default"],
            subset["predicted_default"],
            zero_division=0)})

subgroup_metrics = pd.DataFrame(
    subgroup_metrics)

subgroup_metrics

subgroup_display = subgroup_metrics.copy()

subgroup_display[
    "actual_default_rate"
] *= 100

subgroup_display[
    "average_predicted_risk"
] *= 100

subgroup_display[
    "actual_default_rate"
] = subgroup_display[
    "actual_default_rate"
].round(2)

subgroup_display[
    "average_predicted_risk"
] = subgroup_display[
    "average_predicted_risk"
].round(2)

subgroup_display[
    ["precision", "recall", "f1"]
] = subgroup_display[
    ["precision", "recall", "f1"]
].round(3)

subgroup_display

recall_gap = abs(
    subgroup_metrics.loc[
        subgroup_metrics["applicant_group"] == "Non-Thin-File",
        "recall"
    ].iloc[0]
    -
    subgroup_metrics.loc[
        subgroup_metrics["applicant_group"] == "Thin-File",
        "recall"
    ].iloc[0])

print(
    "Recall gap:",
    round(recall_gap, 3))

f1_gap = abs(
    subgroup_metrics.loc[
        subgroup_metrics["applicant_group"] == "Non-Thin-File",
        "f1"
    ].iloc[0]
    -
    subgroup_metrics.loc[
        subgroup_metrics["applicant_group"] == "Thin-File",
        "f1"
    ].iloc[0])

print(
    "F1 gap:",
    round(f1_gap, 3))

subgroup_display[[
        "applicant_group",
        "actual_default_rate",
        "average_predicted_risk"]]

subgroup_display.to_csv(
    "thin_file_bias_analysis.csv",
    index=False)

print("Thin-file bias analysis saved.")

from sklearn.metrics import RocCurveDisplay
RocCurveDisplay.from_predictions(y_test, y_prob_logistic)
plt.savefig("roc_curve.png")

tier_summary["actual_default_rate"] = pricing_df.groupby("risk_tier")["actual_default"].mean() * 100



import os

bias_note = """
# Bias Awareness and Human Oversight

## Potential Proxy Bias

The credit-risk model does not directly include protected characteristics such as gender or location. However, some of the variables used by the model could act as indirect proxies for characteristics that may be correlated with socioeconomic or demographic groups. For example, employment_type may be associated with different socioeconomic circumstances or geographic labour-market patterns. Monthly income can also reflect unequal access to employment opportunities and may correlate with location or other demographic characteristics. Similarly, credit_bureau_score can reflect differences in access to formal credit and therefore may disadvantage applicants who are new to credit or have limited credit histories.

The thin-file population requires particular attention. Applicants with missing credit bureau scores should not automatically be treated as higher-risk simply because they have less traditional credit history. The model deliberately uses UPI inflow and other alternative signals so that applicants can still be assessed when bureau information is unavailable, but this does not eliminate the possibility of indirect bias.

## Human Oversight and Governance

Before deployment, model performance should be monitored across relevant applicant segments, including thin-file status and employment type. Approval and decline rates, default rates, false-positive rates, and model performance should be reviewed periodically to identify potentially unfair outcomes.

A concrete safeguard should be introduced: **a human reviewer should double-check any thin-file applicant who receives a decline recommendation before the decision becomes final.** Borderline or unusually high-risk decisions should also be eligible for human review. Model thresholds should be reviewed periodically, and the model should not be deployed permanently without ongoing fairness, performance, and outcome monitoring.

Human oversight is therefore an important control alongside the model rather than a replacement for the model.
"""

# Create the directory if it doesn't exist
os.makedirs("credit_risk_lending_ml", exist_ok=True)

with open(
    "credit_risk_lending_ml/bias_awareness.md",
    "w",
    encoding="utf-8"
) as f:
    f.write(bias_note)

print("Created: bias_awareness.md")
print("Word count:", len(bias_note.split()))

# Display the actual model comparison table
print(model_comparison)

import os

print(
    "Root README exists:",
    os.path.exists("README.md")
)

with open("README.md", "w", encoding="utf-8") as f:
    f.write("# Payments & Fraud Analytics Project\n\n")

print("README.md created successfully.")