# -*- coding: utf-8 -*-
"""Part3_AI_Advisory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyUQ7nYhk2n4TlKnaSF_-GYds9WHPBzk
"""

import pandas as pd

STOCK_UNIVERSE = {
    "PAYFIN":  {"beta": 1.35, "analyst_expected_return": 0.16, "std_dev": 0.28},
    "PAYRETAIL": {"beta": 0.85, "analyst_expected_return": 0.11, "std_dev": 0.17},
    "PAYINFRA": {"beta": 1.10, "analyst_expected_return": 0.135, "std_dev": 0.22},
    "PAYGOLD": {"beta": 0.20, "analyst_expected_return": 0.08, "std_dev": 0.12},
    "PAYBOND": {"beta": 0.05, "analyst_expected_return": 0.065, "std_dev": 0.04},
    "PAYTECH": {"beta": 1.55, "analyst_expected_return": 0.19, "std_dev": 0.34},}
RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13

print("Available stocks:")

for ticker, data in STOCK_UNIVERSE.items():
    print(ticker,
        "Beta =", data["beta"],
        "| Analyst Return =", data["analyst_expected_return"],
        "| Std Dev =", data["std_dev"])

INVESTOR_PROFILES = [
    {"investor_id": "INV01", "risk_tolerance": "Conservative", "horizon_years": 3, "investment_amount_inr": 200000},
    {"investor_id": "INV02", "risk_tolerance": "Moderate", "horizon_years": 7, "investment_amount_inr": 500000},
    {"investor_id": "INV03", "risk_tolerance": "Aggressive", "horizon_years": 12, "investment_amount_inr": 300000},
    {"investor_id": "INV04", "risk_tolerance": "Moderate", "horizon_years": 5, "investment_amount_inr": 800000},
    {"investor_id": "INV05", "risk_tolerance": "Aggressive", "horizon_years": 2, "investment_amount_inr": 150000},]

investor_df = pd.DataFrame(INVESTOR_PROFILES)

investor_df

DISCLOSURE_SNIPPETS = [
    "doc_01: Assuming input costs remain stable through the next two quarters, we expect "
    "margins to hold at current levels.",
    "doc_02: The company faces an ongoing litigation matter related to a former vendor "
    "contract; management believes the exposure is not material.",
    "doc_03: Our top three customers together account for approximately 42 percent of "
    "total revenue this year.",
    "doc_04: We remain cautiously optimistic about demand recovery, though visibility "
    "beyond the next quarter is limited given macro uncertainty.",
    "doc_05: The board is confident in the long-term strategy and has approved an "
    "expanded capital expenditure plan for the coming year.",
    "doc_06: A recent regulatory notice has been received regarding data-localization "
    "compliance; the company is in active dialogue with the regulator.",]

for snippet in DISCLOSURE_SNIPPETS:
    print(snippet)
    print("-" * 80)

print("DATA CHECK")

print("Number of stocks:", len(STOCK_UNIVERSE))

print("Number of investor profiles:",len(INVESTOR_PROFILES))

print("Number of disclosure snippets:",len(DISCLOSURE_SNIPPETS))

print("Risk-free rate:",RISK_FREE_RATE)

print("Market return:", MARKET_RETURN)

ALLOCATION_RULES = {
    "Conservative": [
        "PAYBOND",
        "PAYGOLD",
        "PAYRETAIL"],

    "Moderate": [
        "PAYRETAIL",
        "PAYINFRA",
        "PAYGOLD"],

    "Aggressive": [
        "PAYTECH",
        "PAYFIN",
        "PAYINFRA"]}

for risk, tickers in ALLOCATION_RULES.items():
    print(risk, "→", tickers)

PORTFOLIO_WEIGHT = 1 / 3

print("Weight of each stock:", PORTFOLIO_WEIGHT)
print("Total weight:", PORTFOLIO_WEIGHT * 3)

def get_stock_data(ticker):
    """
    Simulated stock-data tool.
    Looks up stock information from STOCK_UNIVERSE.
    """

    if ticker not in STOCK_UNIVERSE:
        raise ValueError(
            f"Stock {ticker} not found in STOCK_UNIVERSE.")

    return STOCK_UNIVERSE[ticker]

get_stock_data("PAYFIN")

def calculate_capm_return(beta):
    """
    Calculate CAPM expected return using:

    Rf + beta * (Rm - Rf)
    """

    return (RISK_FREE_RATE
        + beta * (
            MARKET_RETURN - RISK_FREE_RATE))

payfin_data = get_stock_data("PAYFIN")

payfin_capm_return = calculate_capm_return(payfin_data["beta"])

print("PAYFIN CAPM expected return:",payfin_capm_return)

print("PAYFIN CAPM expected return (%):",payfin_capm_return * 100)

for ticker in STOCK_UNIVERSE:

    data = get_stock_data(ticker)

    capm_return = calculate_capm_return(
        data["beta"])

    print(ticker, "→",
        round(capm_return * 100, 2),
        "%")

PAIRWISE_CORRELATION = 0.3

import math

def calculate_portfolio_metrics(tickers):

    weights = {
        ticker: 1 / 3
        for ticker in tickers}

    # Get stock data using the required tool
    stock_data = {
        ticker: get_stock_data(ticker)
        for ticker in tickers}

    # CAPM expected return

    capm_returns = {
        ticker: calculate_capm_return(
            stock_data[ticker]["beta"])
        for ticker in tickers}

    portfolio_return = sum(
        weights[ticker] * capm_returns[ticker]
        for ticker in tickers)

    # Portfolio variance

    variance = 0

    # Individual variance terms
    for ticker in tickers:

        weight = weights[ticker]
        sigma = stock_data[ticker]["std_dev"]

        variance += (
            weight ** 2
            * sigma ** 2)

    # Covariance terms
    for i in range(len(tickers)):

        for j in range(i + 1, len(tickers)):

            ticker_i = tickers[i]
            ticker_j = tickers[j]

            weight_i = weights[ticker_i]
            weight_j = weights[ticker_j]

            sigma_i = stock_data[ticker_i]["std_dev"]
            sigma_j = stock_data[ticker_j]["std_dev"]

            covariance = (
                PAIRWISE_CORRELATION
                * sigma_i
                * sigma_j)

            variance += (
                2
                * weight_i
                * weight_j
                * covariance)

    portfolio_std = math.sqrt(variance)

    return {
        "tickers": tickers,
        "weights": weights,
        "capm_returns": capm_returns,
        "portfolio_return": portfolio_return,
        "portfolio_variance": variance,
        "portfolio_std": portfolio_std}

conservative_result = calculate_portfolio_metrics(
    ALLOCATION_RULES["Conservative"])

conservative_result

print("Conservative portfolio standard deviation:",
    round(
        conservative_result["portfolio_std"] * 100,
        2),
    "%")

print(
    "Conservative portfolio standard deviation:",
    round(
        conservative_result["portfolio_std"] * 100,
        2),
    "%")

moderate_result = calculate_portfolio_metrics(
    ALLOCATION_RULES["Moderate"])

print(
    "Moderate portfolio standard deviation:",
    round(
        moderate_result["portfolio_std"] * 100,
        2),
    "%")

aggressive_result = calculate_portfolio_metrics(
    ALLOCATION_RULES["Aggressive"])

print(
    "Aggressive portfolio standard deviation:",
    round(
        aggressive_result["portfolio_std"] * 100,
        2),
    "%")

print("PORTFOLIO CHECK")

for risk_tolerance in [
    "Conservative",
    "Moderate",
    "Aggressive"]:

    result = calculate_portfolio_metrics(
        ALLOCATION_RULES[risk_tolerance])

    print(
        risk_tolerance,
        "| Return:",
        round(
            result["portfolio_return"] * 100,
            2),
        "%","| Risk:",
        round(
            result["portfolio_std"] * 100,
            2),
        "%")

HUMAN_REVIEW_THRESHOLD = 0.20

def check_human_escalation(portfolio_std):

    if portfolio_std > HUMAN_REVIEW_THRESHOLD:
        return "ESCALATED_TO_HUMAN_ADVISOR"

    return "AUTO_FINALIZE"

check_human_escalation(
    conservative_result["portfolio_std"])

check_human_escalation(
    moderate_result["portfolio_std"])

check_human_escalation(
    aggressive_result["portfolio_std"])

def advisory_agent(investor):

    # THINK

    risk_tolerance = investor["risk_tolerance"]

    tickers = ALLOCATION_RULES[
        risk_tolerance]

    print("\n" + "=" * 60)
    print("THINK")
    print(f"Investor {investor['investor_id']}")
    print(f"Risk tolerance: {risk_tolerance}")
    print(f"Selected allocation: {tickers}")

    # ACT

    print("\nACT")
    print("Calling get_stock_data()...")

    result = calculate_portfolio_metrics(tickers)

    # OBSERVE

    print("\nOBSERVE")

    print(
        "Portfolio expected return:",
        round(
            result["portfolio_return"] * 100,
            2),
        "%")

    print(
        "Portfolio volatility:",
        round(
            result["portfolio_std"] * 100,
            2),
        "%")

    # DECISION

    decision = check_human_escalation(
        result["portfolio_std"])

    print("\nDECISION")
    print(decision)

    result["investor_id"] = investor[
        "investor_id"]

    result["risk_tolerance"] = risk_tolerance

    result["decision"] = decision

    return result

def advisory_agent(investor):

    # THINK
    # Understand the investor's risk profile and select the appropriate
    # portfolio allocation rules.

    # your existing investor/risk-profile code


    # ACT
    # Select the stocks and calculate the portfolio metrics
    # according to the investor's risk profile.

    # your existing portfolio calculation code


    # OBSERVE
    # Review portfolio volatility and determine whether the result
    # can be finalized automatically or requires human review.

    # your existing escalation/decision code

result_inv01 = advisory_agent(
    INVESTOR_PROFILES[0])

result_inv01 = advisory_agent(
    INVESTOR_PROFILES[2])

all_results = []

for investor in INVESTOR_PROFILES:

    result = advisory_agent(investor)

    all_results.append(result)

agent_results = pd.DataFrame([{
        "investor_id": result["investor_id"],
        "risk_tolerance": result["risk_tolerance"],
        "tickers": ", ".join(
            result["tickers"]),
        "portfolio_return": result[
            "portfolio_return"],
        "portfolio_std": result[
            "portfolio_std"],
        "decision": result["decision"]}
    for result in all_results])

agent_results

agent_results[
    "portfolio_return_pct"
] = (
    agent_results[
        "portfolio_return"
    ] * 100)

agent_results[
    "portfolio_std_pct"
] = (
    agent_results[
        "portfolio_std"
    ] * 100)

agent_results[[
        "investor_id",
        "risk_tolerance",
        "tickers",
        "portfolio_return_pct",
        "portfolio_std_pct",
        "decision"]]

print(agent_results[[
            "investor_id",
            "risk_tolerance",
            "portfolio_std_pct",
            "decision"]])

agent_results.to_csv("portfolio_advisory_results.csv",
    index=False)

print("portfolio_advisory_results.csv saved.")

def mock_llm_recommendation(
    investor_id,
    risk_tolerance,
    tickers,
    portfolio_return,
    portfolio_std,
    decision):

    return (
        f"Investor {investor_id} has a "
        f"{risk_tolerance.lower()} risk profile. "
        f"The prescribed portfolio consists of "
        f"{', '.join(tickers)}. "
        f"The portfolio has an estimated CAPM return "
        f"of {portfolio_return * 100:.2f}% and estimated "
        f"volatility of {portfolio_std * 100:.2f}%. "
        f"Current decision status: {decision}.")

test_recommendation = mock_llm_recommendation(
    investor_id=result_inv01["investor_id"],
    risk_tolerance=result_inv01["risk_tolerance"],
    tickers=result_inv01["tickers"],
    portfolio_return=result_inv01["portfolio_return"],
    portfolio_std=result_inv01["portfolio_std"],
    decision=result_inv01["decision"])

print(test_recommendation)

def generate_advisory_message(result):

    if result["decision"] == "ESCALATED_TO_HUMAN_ADVISOR":

        return (
            f"Investor {result['investor_id']} has a "
            f"{result['risk_tolerance'].lower()} risk profile. "
            f"The prescribed portfolio contains "
            f"{', '.join(result['tickers'])}. "
            f"The estimated portfolio volatility is "
            f"{result['portfolio_std'] * 100:.2f}%, "
            f"which exceeds the 20% human-review threshold. "
            f"Recommendation requires review by a human advisor "
            f"before finalization.")

    return mock_llm_recommendation(
        investor_id=result["investor_id"],
        risk_tolerance=result["risk_tolerance"],
        tickers=result["tickers"],
        portfolio_return=result["portfolio_return"],
        portfolio_std=result["portfolio_std"],
        decision=result["decision"])

print(generate_advisory_message(result_inv01))

result_inv03 = advisory_agent(INVESTOR_PROFILES[2])

print(generate_advisory_message(result_inv03))

agent_results["recommendation"] = [
    generate_advisory_message(result)
    for result in all_results]

agent_results[[
        "investor_id",
        "risk_tolerance",
        "portfolio_std_pct",
        "decision",
        "recommendation"]]

final_advisory_output = agent_results[[
        "investor_id",
        "risk_tolerance",
        "tickers",
        "portfolio_return_pct",
        "portfolio_std_pct",
        "decision",
        "recommendation"]
].copy()

final_advisory_output

final_advisory_output.to_csv(
    "final_advisory_output.csv",
    index=False)

print("final_advisory_output.csv saved.")

escalated = final_advisory_output[
    final_advisory_output["decision"]
    == "ESCALATED_TO_HUMAN_ADVISOR"]

print(escalated[[
        "investor_id",
        "portfolio_std_pct",
        "decision"]])

get_stock_data(ticker)

audit_log = []

for result in all_results:

    audit_log.append({
        "investor_id": result["investor_id"],
        "risk_tolerance": result["risk_tolerance"],
        "selected_stocks": ", ".join(
            result["tickers"]),
        "portfolio_return": result[
            "portfolio_return"],
        "portfolio_volatility": result[
            "portfolio_std"],
        "human_review_threshold": HUMAN_REVIEW_THRESHOLD,
        "decision": result["decision"]})

audit_log = pd.DataFrame(audit_log)

audit_log

audit_log.to_csv(
    "advisory_audit_log.csv",
    index=False)

print("advisory_audit_log.csv saved.")

print("AI ADVISORY CHECK")

print("Total investors:", len(final_advisory_output))

print("Auto-finalized:",
    (final_advisory_output["decision"]
        == "AUTO_FINALIZE"
    ).sum())

print("Human escalations:",
    (final_advisory_output["decision"]
        == "ESCALATED_TO_HUMAN_ADVISOR"
    ).sum())

print("\nExpected:")

print("Total investors = 5")

print("Auto-finalized = 3")

print("Human escalations = 2")

import re

def extract_signals(text):

    text_lower = text.lower()

    risk_flags = []

    # 1. Litigation risk

    if re.search(
        r"\blitigation\b|\blawsuit\b|\blegal\b|\bcourt\b",
        text_lower):
        risk_flags.append("litigation")

    # 2. Regulatory risk

    if re.search(
        r"\bregulatory\b|\bregulator\b|\bcompliance\b",
        text_lower):
        risk_flags.append("regulatory")

    # 3. Customer concentration risk

    if re.search(
        r"top\s+three\s+customers|"
        r"customer[s]?\s+account\s+for|"
        r"customer\s+concentration",
        text_lower):
        risk_flags.append("customer_concentration")

    # Hedging detection

    hedging_detected = bool(
        re.search(
            r"\bassuming\b|"
            r"\bexpect\b|"
            r"\bexpected\b|"
            r"\bcautiously\b|"
            r"\buncertainty\b|"
            r"\bvisibility\b|"
            r"\bmay\b|"
            r"\bmight\b",
            text_lower))

    # Sentiment

    confident_words = [
        "confident",
        "confidence",
        "strong",
        "optimistic",
        "approved"]

    cautious_words = [
        "cautious",
        "cautiously",
        "uncertainty",
        "limited visibility",
        "risk"]

    confident_count = sum(
        word in text_lower
        for word in confident_words)

    cautious_count = sum(
        word in text_lower
        for word in cautious_words)

    if confident_count > cautious_count:
        sentiment = "confident"

    elif cautious_count > confident_count:
        sentiment = "cautious"

    else:
        sentiment = "neutral"

    return {
        "risk_flags": risk_flags,
        "hedging_detected": hedging_detected,
        "sentiment": sentiment}

result_doc01 = extract_signals(
    DISCLOSURE_SNIPPETS[0])

result_doc01

result_doc02 = extract_signals(
    DISCLOSURE_SNIPPETS[1])

result_doc02

result_doc03 = extract_signals(
    DISCLOSURE_SNIPPETS[2])

result_doc03

result_doc04 = extract_signals(
    DISCLOSURE_SNIPPETS[3])

result_doc04

result_doc05 = extract_signals(
    DISCLOSURE_SNIPPETS[4])

result_doc05

result_doc06 = extract_signals(
    DISCLOSURE_SNIPPETS[5])

result_doc06

disclosure_results = []

for snippet in DISCLOSURE_SNIPPETS:

    # Extract document ID
    doc_id = snippet.split(":")[0]

    # Run extraction
    signals = extract_signals(snippet)

    disclosure_results.append({
        "doc_id": doc_id,
        "risk_flags": signals["risk_flags"],
        "hedging_detected": signals[
            "hedging_detected"],
        "sentiment": signals["sentiment"]})

disclosure_df = pd.DataFrame(
    disclosure_results)

disclosure_df

for _, row in disclosure_df.iterrows():

    print(
        row["doc_id"],"→",
        row["risk_flags"])

disclosure_df[[
        "doc_id",
        "hedging_detected"]]

disclosure_df[[
        "doc_id",
        "sentiment"]]

structured_disclosures = {}

for snippet in DISCLOSURE_SNIPPETS:

    doc_id = snippet.split(":")[0]

    structured_disclosures[doc_id] = (
        extract_signals(snippet))

structured_disclosures

import json

print(
    json.dumps(
        structured_disclosures,
        indent=4))

assert "litigation" in (
    structured_disclosures["doc_02"]["risk_flags"]
)

assert "customer_concentration" in (
    structured_disclosures["doc_03"]["risk_flags"]
)

assert "regulatory" in (
    structured_disclosures["doc_06"]["risk_flags"])

assert (
    structured_disclosures["doc_01"][
        "hedging_detected"]
    is True)

assert (
    structured_disclosures["doc_04"][
        "hedging_detected"]
    is True)

assert (
    structured_disclosures["doc_05"][
        "sentiment"]
    == "confident")

print("All required disclosure checks passed!")

disclosure_df.to_csv(
    "structured_disclosure_extraction.csv",
    index=False)

print("structured_disclosure_extraction.csv saved.")

with open(
    "structured_disclosures.json",
    "w"
) as file:

    json.dump(
        structured_disclosures,
        file,
        indent=4)

print("structured_disclosures.json saved.")

debate_ticker = "PAYTECH"

print("Debate ticker:", debate_ticker)

debate_data = get_stock_data(
    debate_ticker)

debate_data

def bull_agent(ticker):

    data = get_stock_data(ticker)

    beta = data["beta"]
    analyst_return = data[
        "analyst_expected_return"]
    std_dev = data["std_dev"]

    argument = (
        f"BULL VIEW — {ticker}: "
        f"The stock has an analyst expected return "
        f"of {analyst_return:.1%} against a beta of "
        f"{beta:.2f}, indicating attractive upside "
        f"relative to its market sensitivity. "
        f"The stock's {std_dev:.1%} standard deviation "
        f"represents meaningful volatility, but the "
        f"potential return may justify that risk for "
        f"an investor with sufficient risk tolerance.")

    return argument

bull_argument = bull_agent(
    debate_ticker)

print(bull_argument)

def bear_agent(ticker):

    data = get_stock_data(ticker)

    beta = data["beta"]
    analyst_return = data[
        "analyst_expected_return"]
    std_dev = data["std_dev"]

    argument = (
        f"BEAR VIEW — {ticker}: "
        f"The stock carries substantial risk, with a "
        f"standard deviation of {std_dev:.1%} and a "
        f"beta of {beta:.2f}, indicating high sensitivity "
        f"to market movements. Although the analyst "
        f"expected return is {analyst_return:.1%}, the "
        f"high volatility means investors could experience "
        f"large fluctuations and should consider their "
        f"risk capacity before investing.")

    return argument

bear_argument = bear_agent(
    debate_ticker)

print(bear_argument)

def synthesizer_agent(
    ticker,
    bull_argument,
    bear_argument):

    data = get_stock_data(ticker)

    beta = data["beta"]
    analyst_return = data[
        "analyst_expected_return"]
    std_dev = data["std_dev"]

    synthesis = (
        f"SYNTHESIS — {ticker}: "
        f"The bull case is supported by the analyst "
        f"expected return of {analyst_return:.1%}, while "
        f"the bear case highlights the stock's high "
        f"beta of {beta:.2f} and {std_dev:.1%} volatility. "
        f"Overall, {ticker} may offer attractive upside "
        f"but should be considered primarily by investors "
        f"who can tolerate substantial fluctuations.")

    return synthesis

synthesis = synthesizer_agent(
    debate_ticker,
    bull_argument,
    bear_argument)

print(synthesis)

def run_debate(ticker):

    print("=" * 70)
    print(f"3-AGENT DEBATE: {ticker}")
    print("=" * 70)

    # Agent 1: Bull

    bull = bull_agent(ticker)

    print("\n[BULL AGENT]")
    print(bull)

    # Agent 2: Bear

    bear = bear_agent(ticker)

    print("\n[BEAR AGENT]")
    print(bear)

    # Agent 3: Synthesizer

    synthesis = synthesizer_agent(
        ticker,
        bull,
        bear)

    print("\n[SYNTHESIZER]")
    print(synthesis)

    return {
        "ticker": ticker,
        "bull_argument": bull,
        "bear_argument": bear,
        "synthesis": synthesis}

debate_result = run_debate("PAYTECH")

expected_values = [
    f"{debate_data['beta']:.2f}",
    f"{debate_data['analyst_expected_return']:.1%}",
    f"{debate_data['std_dev']:.1%}"]

for value in expected_values:

    assert value in debate_result["bull_argument"]

    assert value in debate_result["bear_argument"]

print("All actual stock values appear in the debate arguments!")

assert debate_ticker in (
    debate_result["synthesis"])

assert (
    f"{debate_data['beta']:.2f}"
    in debate_result["synthesis"])

assert (
    f"{debate_data['std_dev']:.1%}"
    in debate_result["synthesis"])

print("Synthesizer validation passed!")

debate_output = pd.DataFrame({
    "ticker": [debate_result["ticker"]],
    "bull_argument": [
        debate_result["bull_argument"]],
    "bear_argument": [
        debate_result["bear_argument"]],
    "synthesis": [
        debate_result["synthesis"]]})

debate_output

debate_output.to_csv(
    "debate_output.csv",
    index=False)

print("debate_output.csv saved.")

DCF_ASSUMPTIONS = {
    "ebit_inr": 100_000_000,
    "tax_rate": 0.25,
    "da_inr": 15_000_000,
    "capex_inr": 20_000_000,
    "delta_nwc_inr": 5_000_000,

    "yearly_growth_rates": [
        0.12,
        0.10,
        0.08,
        0.07,
        0.06],

    "terminal_growth_rate": 0.05,

    "cost_of_debt": 0.08,

    "equity_weight": 0.70,
    "debt_weight": 0.30,

    "ebitda_inr": 80_000_000,
    "ev_ebitda_multiple": 10.0}

print(
    "Total capital weight:",
    DCF_ASSUMPTIONS["equity_weight"]
    + DCF_ASSUMPTIONS["debt_weight"])

def calculate_fcff(
    ebit,
    tax_rate,
    da,
    capex,
    delta_nwc):

    fcff = (
        ebit * (1 - tax_rate)
        + da
        - capex
        - delta_nwc)

    return fcff

base_fcff = calculate_fcff(
    DCF_ASSUMPTIONS["ebit_inr"],
    DCF_ASSUMPTIONS["tax_rate"],
    DCF_ASSUMPTIONS["da_inr"],
    DCF_ASSUMPTIONS["capex_inr"],
    DCF_ASSUMPTIONS["delta_nwc_inr"])

print("Base FCFF:",base_fcff)

print("Base FCFF in crore:", base_fcff / 10_000_000)

dcf_ticker = "PAYFIN"

dcf_stock_data = get_stock_data(
    dcf_ticker)

dcf_beta = dcf_stock_data["beta"]

print("DCF stock:", dcf_ticker)

print("Beta:", dcf_beta)

RISK_FREE_RATE
MARKET_RETURN

print("Risk-free rate:", RISK_FREE_RATE)
print("Market return:", MARKET_RETURN)

RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13

def calculate_cost_of_equity(
    risk_free_rate,
    market_return,
    beta):

    return (
        risk_free_rate
        + beta
        * (market_return
            - risk_free_rate))

cost_of_equity = calculate_cost_of_equity(
    RISK_FREE_RATE,
    MARKET_RETURN,
    dcf_beta)

print("Cost of equity:", cost_of_equity)

print("Cost of equity (%):", cost_of_equity * 100)

def calculate_wacc(
    cost_of_equity,
    cost_of_debt,
    tax_rate,
    equity_weight,
    debt_weight):

    return (
        equity_weight * cost_of_equity
        +
        debt_weight
        * cost_of_debt
        * (1 - tax_rate))

wacc = calculate_wacc(
    cost_of_equity,
    DCF_ASSUMPTIONS["cost_of_debt"],
    DCF_ASSUMPTIONS["tax_rate"],
    DCF_ASSUMPTIONS["equity_weight"],
    DCF_ASSUMPTIONS["debt_weight"])

print("WACC:",wacc)

print("WACC (%):", wacc * 100)

terminal_growth = (
    DCF_ASSUMPTIONS[
        "terminal_growth_rate"])

print("WACC - terminal growth:",
    (wacc - terminal_growth) * 100,
    "%")

assert (
    wacc - terminal_growth
) >= 0.03

print("Terminal growth constraint PASSED.")

def project_fcff(
    base_fcff,
    growth_rates):

    projections = []

    previous_fcff = base_fcff

    for year, growth in enumerate(
        growth_rates,
        start=1):

        current_fcff = (
            previous_fcff
            * (1 + growth))

        projections.append({
            "year": year,
            "growth_rate": growth,
            "fcff": current_fcff})

        previous_fcff = current_fcff

    return pd.DataFrame(projections)

fcff_projection = project_fcff(
    base_fcff,
    DCF_ASSUMPTIONS[
        "yearly_growth_rates"])

fcff_projection

def calculate_terminal_value(
    final_fcff,
    terminal_growth,
    wacc):

    if wacc <= terminal_growth:
        raise ValueError(
            "WACC must be greater than terminal growth.")

    return (
        final_fcff
        * (1 + terminal_growth)
        / (wacc - terminal_growth))

def calculate_terminal_value(
    final_fcff,
    terminal_growth,
    wacc):

    if wacc <= terminal_growth:
        raise ValueError(
            "WACC must be greater than terminal growth.")

    return (
        final_fcff
        * (1 + terminal_growth)
        / (wacc - terminal_growth))

fcff_projection["discount_factor"] = (
    1
    / (
        1 + wacc
    ) ** fcff_projection["year"])

fcff_projection["pv_fcff"] = (
    fcff_projection["fcff"]
    * fcff_projection["discount_factor"])

fcff_projection

final_fcff = fcff_projection.loc[fcff_projection.index[-1], 'fcff']

terminal_value = calculate_terminal_value(
    final_fcff,
    DCF_ASSUMPTIONS["terminal_growth_rate"],
    wacc)

pv_terminal_value = (
    terminal_value
    / (
        1 + wacc
    ) ** 5)

print("Terminal Value:", terminal_value)
print("PV of terminal value:", pv_terminal_value)

print("PV of terminal value in crore:", pv_terminal_value / 10_000_000)

pv_explicit_fcff = (
    fcff_projection["pv_fcff"]
    .sum())

enterprise_value = (
    pv_explicit_fcff
    + pv_terminal_value)

print("PV of explicit FCFF:", pv_explicit_fcff)

print("Enterprise Value:", enterprise_value)

print("Enterprise Value in crore:", enterprise_value / 10_000_000)

dcf_table = fcff_projection.copy()

dcf_table["fcff_crore"] = (
    dcf_table["fcff"]
    / 10_000_000)

dcf_table["pv_fcff_crore"] = (
    dcf_table["pv_fcff"]
    / 10_000_000)

dcf_table[[
        "year",
        "growth_rate",
        "fcff_crore",
        "discount_factor",
        "pv_fcff_crore"]]

def calculate_dcf_value(
    fcff_projection,
    terminal_growth,
    wacc):

    if wacc <= terminal_growth:
        return np.nan

    pv_fcff = 0

    for _, row in fcff_projection.iterrows():

        year = row["year"]
        fcff = row["fcff"]

        pv_fcff += (
            fcff
            / (1 + wacc) ** year)

    final_fcff = fcff_projection.iloc[-1]["fcff"]

    terminal_value = (
        final_fcff
        * (1 + terminal_growth)
        / (wacc - terminal_growth))

    pv_terminal = (
        terminal_value
        / (1 + wacc) ** 5)

    return pv_fcff + pv_terminal

wacc_sensitivity = [
    wacc - 0.01,
    wacc,
    wacc + 0.01]

growth_sensitivity = [
    terminal_growth - 0.01,
    terminal_growth,
    terminal_growth + 0.01]

sensitivity_table = pd.DataFrame(
    index=[
        f"{rate:.2%}"
        for rate in wacc_sensitivity],
    columns=[
        f"{growth:.2%}"
        for growth in growth_sensitivity])

for wacc_value in wacc_sensitivity:

    for growth_value in growth_sensitivity:

        sensitivity_table.loc[
            f"{wacc_value:.2%}",
            f"{growth_value:.2%}"] = (
            calculate_dcf_value(
                fcff_projection,
                growth_value,
                wacc_value)
            / 10_000_000)

sensitivity_table

worst_case_wacc = min(
    wacc_sensitivity)

worst_case_growth = max(
    growth_sensitivity)

worst_case_gap = (
    worst_case_wacc
    - worst_case_growth)

print(
    "Worst-case WACC:",
    worst_case_wacc * 100,
    "%")

print(
    "Worst-case terminal growth:",
    worst_case_growth * 100,
    "%")

print(
    "Worst-case gap:",
    worst_case_gap * 100,
    "%")

assert worst_case_gap >= 0.01

print("Sensitivity WACC > growth constraint PASSED.")

ev_ebitda_value = (
    DCF_ASSUMPTIONS["ebitda_inr"]
    * DCF_ASSUMPTIONS[
        "ev_ebitda_multiple"])

print(
    "EV/EBITDA valuation:",
    ev_ebitda_value)

print(
    "EV/EBITDA valuation in crore:",
    ev_ebitda_value / 10_000_000)

print("\nDCF vs EV/EBITDA Comparison")

print(
    f"DCF Enterprise Value: "
    f"₹{enterprise_value:,.0f}"
)

print(
    f"EV/EBITDA Implied Value: "
    f"₹{ev_ebitda_value:,.0f}"
)

if enterprise_value > ev_ebitda_value:
    valuation_comment = (
        "The DCF produces a higher valuation than the "
        "EV/EBITDA cross-check, suggesting that the DCF "
        "assumptions imply greater value than the market "
        "multiple approach."
    )
elif enterprise_value < ev_ebitda_value:
    valuation_comment = (
        "The DCF produces a lower valuation than the "
        "EV/EBITDA cross-check, suggesting that the DCF "
        "assumptions imply a more conservative valuation "
        "than the market multiple approach."
    )
else:
    valuation_comment = (
        "The DCF and EV/EBITDA approaches produce similar "
        "valuations."
    )

print(valuation_comment)

valuation_difference = (
    enterprise_value
    - ev_ebitda_value)

valuation_difference_pct = (
    valuation_difference
    / ev_ebitda_value)

print(
    "DCF EV:",
    enterprise_value / 10_000_000,
    "crore")

print(
    "EV/EBITDA:",
    ev_ebitda_value / 10_000_000,
    "crore")

print(
    "DCF premium vs EV/EBITDA:",
    valuation_difference_pct * 100,
    "%")

dcf_summary = {
    "ticker_beta_source": dcf_ticker,
    "beta": dcf_beta,
    "cost_of_equity": cost_of_equity,
    "cost_of_debt": DCF_ASSUMPTIONS[
        "cost_of_debt"],
    "wacc": wacc,
    "base_fcff": base_fcff,
    "terminal_growth": terminal_growth,
    "terminal_value": terminal_value,
    "enterprise_value": enterprise_value,
    "ev_ebitda_value": ev_ebitda_value,
    "worst_case_wacc_growth_gap": (
        worst_case_gap)}

dcf_summary

dcf_summary = {
    "ticker_beta_source": dcf_ticker,
    "beta": dcf_beta,
    "cost_of_equity": cost_of_equity,
    "cost_of_debt": DCF_ASSUMPTIONS[
        "cost_of_debt"],
    "wacc": wacc,
    "base_fcff": base_fcff,
    "terminal_growth": terminal_growth,
    "terminal_value": terminal_value,
    "enterprise_value": enterprise_value,
    "ev_ebitda_value": ev_ebitda_value,
    "worst_case_wacc_growth_gap": (
        worst_case_gap)}

dcf_summary

sensitivity_table.to_csv("dcf_sensitivity_table.csv")

print("dcf_sensitivity_table.csv saved.")

dcf_table.to_csv(
    "dcf_fcff_projection.csv",
    index=False)

print("dcf_fcff_projection.csv saved.")

assert len(fcff_projection) == 5

assert (terminal_growth < wacc)

assert (worst_case_gap >= 0.01)

assert (enterprise_value > 0)

assert (ev_ebitda_value > 0)

print("=" * 60)
print("DCF MODEL VALIDATION PASSED")
print("=" * 60)

print("✓ 5-year FCFF projection")
print("✓ CAPM cost of equity")
print("✓ WACC calculation")
print("✓ Terminal value")
print("✓ Enterprise value")
print("✓ 3×3 sensitivity table")
print("✓ WACC > terminal growth check")
print("✓ EV/EBITDA cross-check")

print("FINAL PART 3 VERIFICATION")

print("\n1. STOCKS")
print("Number of stocks:", len(STOCK_UNIVERSE))

print("\n2. INVESTORS")
print("Number of investors:", len(INVESTOR_PROFILES))

print("\n3. PORTFOLIO RESULTS")

for result in all_results:
    print(
        result["investor_id"],
        "|",
        result["risk_tolerance"],
        "| Std Dev:",
        f"{result['portfolio_std']:.2%}",
        "| Decision:",
        result["decision"]
    )

import shutil
import os

source = "part3_ai_advisory.py"

print("File exists:", os.path.exists(source))

from google.colab import files

uploaded = files.upload()

import os

PART3 = "ai_advisory_blockchain"

os.makedirs(PART3, exist_ok=True)

print("Ready:", PART3)

import os

print("Python files in Colab:")

for f in os.listdir():
    if f.endswith(".py"):
        print("✅", f)

stock_code = '''STOCK_UNIVERSE = {
    "PAYFIN": {"beta": 1.35, "analyst_expected_return": 0.16, "std_dev": 0.28},
    "PAYRETAIL": {"beta": 0.85, "analyst_expected_return": 0.11, "std_dev": 0.17},
    "PAYINFRA": {"beta": 1.10, "analyst_expected_return": 0.135, "std_dev": 0.22},
    "PAYGOLD": {"beta": 0.20, "analyst_expected_return": 0.08, "std_dev": 0.12},
    "PAYBOND": {"beta": 0.05, "analyst_expected_return": 0.065, "std_dev": 0.04},
    "PAYTECH": {"beta": 1.55, "analyst_expected_return": 0.19, "std_dev": 0.34}
}

RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13
'''

with open(
    f"{PART3}/stock_universe.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(stock_code)

print("Created:", f"{PART3}/stock_universe.py")

investor_code = '''INVESTOR_PROFILES = [
    {
        "investor_id": "INV01",
        "risk_tolerance": "Conservative",
        "horizon_years": 3,
        "investment_amount_inr": 200000
    },
    {
        "investor_id": "INV02",
        "risk_tolerance": "Moderate",
        "horizon_years": 7,
        "investment_amount_inr": 500000
    },
    {
        "investor_id": "INV03",
        "risk_tolerance": "Aggressive",
        "horizon_years": 12,
        "investment_amount_inr": 300000
    },
    {
        "investor_id": "INV04",
        "risk_tolerance": "Moderate",
        "horizon_years": 5,
        "investment_amount_inr": 800000
    },
    {
        "investor_id": "INV05",
        "risk_tolerance": "Aggressive",
        "horizon_years": 2,
        "investment_amount_inr": 150000
    }
]
'''

with open(
    f"{PART3}/investor_profiles.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(investor_code)

print("Created:", f"{PART3}/investor_profiles.py")

disclosure_code = '''DISCLOSURE_SNIPPETS = [
    "doc_01: Assuming input costs remain stable through the next two quarters, we expect margins to hold at current levels.",
    "doc_02: The company faces an ongoing litigation matter related to a former vendor contract; management believes the exposure is not material.",
    "doc_03: Our top three customers together account for approximately 42 percent of total revenue this year.",
    "doc_04: We remain cautiously optimistic about demand recovery, though visibility beyond the next quarter is limited given macro uncertainty.",
    "doc_05: The board is confident in the long-term strategy and has approved an expanded capital expenditure plan for the coming year.",
    "doc_06: A recent regulatory notice has been received regarding data-localization compliance; the company is in active dialogue with the regulator."
]
'''

with open(
    f"{PART3}/disclosure_snippets.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(disclosure_code)

print("Created:", f"{PART3}/disclosure_snippets.py")

import os

print("Files created so far:")

for file in sorted(os.listdir(PART3)):
    print("✅", file)

advisory_agent_code = '''import math

from stock_universe import (
    STOCK_UNIVERSE,
    RISK_FREE_RATE,
    MARKET_RETURN
)


PAIRWISE_CORRELATION = 0.3
HUMAN_REVIEW_THRESHOLD = 0.20


ALLOCATION_RULES = {
    "Conservative": [
        "PAYBOND",
        "PAYGOLD",
        "PAYRETAIL"
    ],
    "Moderate": [
        "PAYRETAIL",
        "PAYINFRA",
        "PAYGOLD"
    ],
    "Aggressive": [
        "PAYTECH",
        "PAYFIN",
        "PAYINFRA"
    ]
}


def get_stock_data(ticker):
    if ticker not in STOCK_UNIVERSE:
        raise ValueError(f"Unknown ticker: {ticker}")

    return STOCK_UNIVERSE[ticker]


def calculate_capm_return(beta):
    return (
        RISK_FREE_RATE
        + beta * (MARKET_RETURN - RISK_FREE_RATE)
    )


def calculate_portfolio_metrics(tickers):

    weights = {
        ticker: 1 / len(tickers)
        for ticker in tickers
    }

    stock_data = {
        ticker: get_stock_data(ticker)
        for ticker in tickers
    }

    capm_returns = {
        ticker: calculate_capm_return(
            stock_data[ticker]["beta"]
        )
        for ticker in tickers
    }

    portfolio_return = sum(
        weights[ticker] * capm_returns[ticker]
        for ticker in tickers
    )

    variance = 0.0

    # Individual variance
    for ticker in tickers:

        weight = weights[ticker]
        sigma = stock_data[ticker]["std_dev"]

        variance += (
            weight ** 2 * sigma ** 2
        )

    # Pairwise covariance
    for i in range(len(tickers)):

        for j in range(i + 1, len(tickers)):

            ticker_i = tickers[i]
            ticker_j = tickers[j]

            covariance = (
                PAIRWISE_CORRELATION
                * stock_data[ticker_i]["std_dev"]
                * stock_data[ticker_j]["std_dev"]
            )

            variance += (
                2
                * weights[ticker_i]
                * weights[ticker_j]
                * covariance
            )

    portfolio_std = math.sqrt(variance)

    return {
        "tickers": tickers,
        "weights": weights,
        "capm_returns": capm_returns,
        "portfolio_return": portfolio_return,
        "portfolio_variance": variance,
        "portfolio_std": portfolio_std
    }


def mock_recommendation(
    investor_id,
    risk_tolerance,
    tickers,
    portfolio_return,
    portfolio_std
):

    return (
        f"Investor {investor_id} has a "
        f"{risk_tolerance.lower()} risk profile. "
        f"The prescribed portfolio consists of "
        f"{', '.join(tickers)}. "
        f"Estimated CAPM return is "
        f"{portfolio_return:.2%} and estimated "
        f"portfolio volatility is "
        f"{portfolio_std:.2%}."
    )


def advisory_agent(investor):

    investor_id = investor["investor_id"]
    risk_tolerance = investor["risk_tolerance"]

    tickers = ALLOCATION_RULES[risk_tolerance]

    stock_data = {
        ticker: get_stock_data(ticker)
        for ticker in tickers
    }

    metrics = calculate_portfolio_metrics(
        tickers
    )

    portfolio_std = metrics["portfolio_std"]

    if portfolio_std > HUMAN_REVIEW_THRESHOLD:

        decision = "ESCALATED_TO_HUMAN_ADVISOR"
        recommendation = None

    else:

        decision = "AUTO_FINALIZE"

        recommendation = mock_recommendation(
            investor_id,
            risk_tolerance,
            tickers,
            metrics["portfolio_return"],
            portfolio_std
        )

    return {
        "investor_id": investor_id,
        "risk_tolerance": risk_tolerance,
        "tickers": tickers,
        "weights": metrics["weights"],
        "stock_data": stock_data,
        "portfolio_return": metrics["portfolio_return"],
        "portfolio_variance": metrics["portfolio_variance"],
        "portfolio_std": portfolio_std,
        "decision": decision,
        "recommendation": recommendation
    }


def run_all_investors(investors):

    return [
        advisory_agent(investor)
        for investor in investors
    ]
'''

with open(
    "ai_advisory_blockchain/advisory_agent.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(advisory_agent_code)

print("Created: advisory_agent.py")

import sys

PART3 = "ai_advisory_blockchain"

if PART3 not in sys.path:
    sys.path.insert(0, PART3)

from advisory_agent import advisory_agent
from investor_profiles import INVESTOR_PROFILES

for investor in INVESTOR_PROFILES:

    result = advisory_agent(investor)

    print(
        result["investor_id"],
        "|",
        result["risk_tolerance"],
        "|",
        f"{result['portfolio_std']:.2%}",
        "|",
        result["decision"]
    )

debate_code = '''from stock_universe import STOCK_UNIVERSE


def get_stock_data(ticker):
    if ticker not in STOCK_UNIVERSE:
        raise ValueError(f"Unknown ticker: {ticker}")
    return STOCK_UNIVERSE[ticker]


def bull_agent(ticker):

    data = get_stock_data(ticker)

    beta = data["beta"]
    expected_return = data["analyst_expected_return"]
    std_dev = data["std_dev"]

    return (
        f"BULL VIEW — {ticker}: "
        f"The analyst expected return is "
        f"{expected_return:.1%} with a beta of "
        f"{beta:.2f}. This indicates attractive "
        f"potential upside for an investor who can "
        f"tolerate the stock's {std_dev:.1%} volatility."
    )


def bear_agent(ticker):

    data = get_stock_data(ticker)

    beta = data["beta"]
    expected_return = data["analyst_expected_return"]
    std_dev = data["std_dev"]

    return (
        f"BEAR VIEW — {ticker}: "
        f"Although the analyst expected return is "
        f"{expected_return:.1%}, the beta of "
        f"{beta:.2f} and standard deviation of "
        f"{std_dev:.1%} indicate substantial market "
        f"sensitivity and volatility."
    )


def synthesizer_agent(
    ticker,
    bull_argument,
    bear_argument
):

    data = get_stock_data(ticker)

    beta = data["beta"]
    expected_return = data["analyst_expected_return"]
    std_dev = data["std_dev"]

    return (
        f"SYNTHESIS — {ticker}: "
        f"The bull case highlights the "
        f"{expected_return:.1%} expected return, "
        f"while the bear case highlights the "
        f"{beta:.2f} beta and {std_dev:.1%} volatility. "
        f"Overall, the stock may offer attractive "
        f"upside but is more appropriate for investors "
        f"who can tolerate substantial fluctuations."
    )


def run_debate(ticker="PAYTECH"):

    bull = bull_agent(ticker)
    bear = bear_agent(ticker)

    synthesis = synthesizer_agent(
        ticker,
        bull,
        bear
    )

    return {
        "ticker": ticker,
        "bull_argument": bull,
        "bear_argument": bear,
        "synthesis": synthesis
    }
'''


with open(
    "ai_advisory_blockchain/debate.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(debate_code)

print("Created: debate.py")

from debate import run_debate

debate_result = run_debate("PAYTECH")

print(debate_result["bull_argument"])
print()
print(debate_result["bear_argument"])
print()
print(debate_result["synthesis"])

dcf_code = '''import pandas as pd

from stock_universe import (
    STOCK_UNIVERSE,
    RISK_FREE_RATE,
    MARKET_RETURN
)


DCF_ASSUMPTIONS = {
    "ebit_inr": 100_000_000,
    "tax_rate": 0.25,
    "da_inr": 15_000_000,
    "capex_inr": 20_000_000,
    "delta_nwc_inr": 5_000_000,

    "growth_rates": [
        0.12,
        0.10,
        0.08,
        0.07,
        0.06
    ],

    "terminal_growth": 0.05,

    "cost_of_debt": 0.08,

    "equity_weight": 0.70,
    "debt_weight": 0.30,

    "dcf_beta_ticker": "PAYFIN",

    "ebitda_inr": 80_000_000,
    "ev_ebitda_multiple": 10.0
}


def calculate_fcff(
    ebit,
    tax_rate,
    da,
    capex,
    delta_nwc
):
    return (
        ebit * (1 - tax_rate)
        + da
        - capex
        - delta_nwc
    )


def calculate_cost_of_equity(beta):
    return (
        RISK_FREE_RATE
        + beta * (
            MARKET_RETURN
            - RISK_FREE_RATE
        )
    )


def calculate_wacc(
    cost_of_equity,
    cost_of_debt,
    tax_rate,
    equity_weight,
    debt_weight
):
    return (
        equity_weight * cost_of_equity
        + debt_weight
        * cost_of_debt
        * (1 - tax_rate)
    )


def project_fcff(
    base_fcff,
    growth_rates
):

    rows = []
    previous_fcff = base_fcff

    for year, growth in enumerate(
        growth_rates,
        start=1
    ):

        fcff = (
            previous_fcff
            * (1 + growth)
        )

        rows.append({
            "year": year,
            "growth_rate": growth,
            "fcff": fcff
        })

        previous_fcff = fcff

    return pd.DataFrame(rows)


def calculate_terminal_value(
    final_fcff,
    terminal_growth,
    wacc
):

    if wacc <= terminal_growth:
        raise ValueError(
            "WACC must exceed terminal growth."
        )

    return (
        final_fcff
        * (1 + terminal_growth)
        / (wacc - terminal_growth)
    )


def calculate_dcf_value(
    projection,
    terminal_growth,
    wacc
):

    if wacc <= terminal_growth:
        return None

    pv_fcff = sum(
        row["fcff"]
        / (1 + wacc) ** row["year"]
        for _, row in projection.iterrows()
    )

    terminal_value = calculate_terminal_value(
        projection.iloc[-1]["fcff"],
        terminal_growth,
        wacc
    )

    pv_terminal = (
        terminal_value
        / (1 + wacc) ** 5
    )

    return pv_fcff + pv_terminal


def run_dcf():

    a = DCF_ASSUMPTIONS

    beta = STOCK_UNIVERSE[
        a["dcf_beta_ticker"]
    ]["beta"]

    base_fcff = calculate_fcff(
        a["ebit_inr"],
        a["tax_rate"],
        a["da_inr"],
        a["capex_inr"],
        a["delta_nwc_inr"]
    )

    cost_of_equity = calculate_cost_of_equity(
        beta
    )

    wacc = calculate_wacc(
        cost_of_equity,
        a["cost_of_debt"],
        a["tax_rate"],
        a["equity_weight"],
        a["debt_weight"]
    )

    terminal_growth = a["terminal_growth"]

    projection = project_fcff(
        base_fcff,
        a["growth_rates"]
    )

    terminal_value = calculate_terminal_value(
        projection.iloc[-1]["fcff"],
        terminal_growth,
        wacc
    )

    enterprise_value = calculate_dcf_value(
        projection,
        terminal_growth,
        wacc
    )

    ev_ebitda_value = (
        a["ebitda_inr"]
        * a["ev_ebitda_multiple"]
    )

    wacc_values = [
        wacc - 0.01,
        wacc,
        wacc + 0.01
    ]

    growth_values = [
        terminal_growth - 0.01,
        terminal_growth,
        terminal_growth + 0.01
    ]

    sensitivity = pd.DataFrame(
        index=[
            f"{x:.2%}"
            for x in wacc_values
        ],
        columns=[
            f"{x:.2%}"
            for x in growth_values
        ]
    )

    for wacc_value in wacc_values:

        for growth_value in growth_values:

            sensitivity.loc[
                f"{wacc_value:.2%}",
                f"{growth_value:.2%}"
            ] = (
                calculate_dcf_value(
                    projection,
                    growth_value,
                    wacc_value
                )
                / 10_000_000
            )

    worst_case_gap = (
        min(wacc_values)
        - max(growth_values)
    )

    if wacc - terminal_growth < 0.03:
        raise AssertionError(
            "WACC minus terminal growth "
            "is below the required 3% margin."
        )

    if worst_case_gap < 0.01:
        raise AssertionError(
            "Worst-case WACC/growth gap "
            "is below 1%."
        )

    return {
        "base_fcff": base_fcff,
        "beta": beta,
        "cost_of_equity": cost_of_equity,
        "wacc": wacc,
        "terminal_growth": terminal_growth,
        "projection": projection,
        "terminal_value": terminal_value,
        "enterprise_value": enterprise_value,
        "ev_ebitda_value": ev_ebitda_value,
        "sensitivity": sensitivity,
        "worst_case_gap": worst_case_gap
    }
'''


with open(
    "ai_advisory_blockchain/dcf_calculator.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(dcf_code)

print("Created: dcf_calculator.py")

from dcf_calculator import run_dcf

dcf_result = run_dcf()

print("Beta:", dcf_result["beta"])
print(
    "Cost of Equity:",
    f"{dcf_result['cost_of_equity']:.2%}"
)
print(
    "WACC:",
    f"{dcf_result['wacc']:.2%}"
)
print(
    "Terminal Growth:",
    f"{dcf_result['terminal_growth']:.2%}"
)

print("\n5-Year FCFF Projection:")
display(
    dcf_result["projection"]
)

print("\n3×3 DCF Sensitivity Table:")
display(
    dcf_result["sensitivity"]
)

print(
    "\nEnterprise Value:",
    f"₹{dcf_result['enterprise_value']:,.0f}"
)

print("\nDCF validation passed.")

import os

print("Part 3 Python files:\n")

required_py = [
    "stock_universe.py",
    "investor_profiles.py",
    "disclosure_snippets.py",
    "advisory_agent.py",
    "extract_disclosure.py",
    "debate.py",
    "dcf_calculator.py"
]

for file in required_py:

    path = os.path.join(
        "ai_advisory_blockchain",
        file
    )

    print(
        "✅" if os.path.exists(path) else "❌",
        file
    )

extract_disclosure_code = '''import re


def extract_signals(text):

    text_lower = text.lower()

    risk_flags = []

    # Litigation
    if re.search(
        r"\\blitigation\\b|\\blawsuit\\b|\\blegal\\b|\\bcourt\\b",
        text_lower
    ):
        risk_flags.append("litigation")

    # Regulatory
    if re.search(
        r"\\bregulatory\\b|\\bregulator\\b|\\bcompliance\\b",
        text_lower
    ):
        risk_flags.append("regulatory")

    # Customer concentration
    if re.search(
        r"top\\s+three\\s+customers|"
        r"customer[s]?\\s+account\\s+for|"
        r"customer\\s+concentration",
        text_lower
    ):
        risk_flags.append("customer_concentration")

    # Hedging / uncertainty
    hedging_detected = bool(
        re.search(
            r"\\bassum(?:e|ing)\\b|"
            r"\\bcautiously\\b|"
            r"\\bvisibility\\b",
            text_lower
        )
    )

    # Sentiment
    if (
        "confident" in text_lower
        or "approved" in text_lower
    ):
        sentiment = "confident"

    elif hedging_detected:
        sentiment = "cautious"

    else:
        sentiment = "neutral"

    return {
        "risk_flags": risk_flags,
        "hedging_detected": hedging_detected,
        "sentiment": sentiment
    }
'''


with open(
    "ai_advisory_blockchain/extract_disclosure.py",
    "w",
    encoding="utf-8"
) as f:
    f.write(extract_disclosure_code)

print("Created: extract_disclosure.py")

from extract_disclosure import extract_signals

tests = {
    "doc_02": "The company faces an ongoing litigation matter.",
    "doc_03": "Our top three customers account for 42 percent of revenue.",
    "doc_06": "A recent regulatory notice has been received regarding compliance.",
    "doc_01": "Assuming input costs remain stable, margins should hold.",
    "doc_05": "The board is confident in the long-term strategy."
}

for doc_id, text in tests.items():
    print(doc_id, "→", extract_signals(text))

import os

required_py = [
    "stock_universe.py",
    "investor_profiles.py",
    "disclosure_snippets.py",
    "advisory_agent.py",
    "extract_disclosure.py",
    "debate.py",
    "dcf_calculator.py"
]

for file in required_py:
    path = os.path.join(
        "ai_advisory_blockchain",
        file
    )

    print(
        "✅" if os.path.exists(path) else "❌",
        file
    )

blockchain_note = """# Blockchain & Crypto Risk Note

## 1. Stablecoin and DeFi/DAO Risk

Stablecoins are crypto-assets designed to maintain a relatively stable value, usually by referencing a fiat currency such as the US dollar. Their stability depends on the quality, liquidity, transparency, and governance of the assets or mechanisms supporting the peg. A loss of confidence, insufficient reserves, liquidity stress, or a rapid increase in redemptions can cause a stablecoin to trade below its intended value.

DeFi protocols introduce additional risks because financial services such as lending, borrowing, and trading can operate through smart contracts rather than traditional intermediaries. Smart-contract vulnerabilities, oracle failures, liquidity shortages, governance attacks, and protocol exploits can create losses that may be difficult to reverse. DeFi and DAO governance can also introduce concentration risk when a small number of token holders have significant voting power.

For a financial institution, these risks should be assessed through counterparty and protocol due diligence, exposure limits, liquidity monitoring, smart-contract and code-audit review, and clear escalation procedures for material incidents.

## 2. Specific Crypto Allocation Recommendation

For a conservative financial-institution portfolio, direct crypto exposure should remain limited because crypto-assets can experience substantial price volatility and liquidity conditions can change rapidly.

A suitable policy recommendation would be to keep direct crypto exposure at no more than 2% of the total portfolio for an investor who has an appropriate risk tolerance and investment horizon. The allocation should be treated as a high-risk satellite allocation rather than a core portfolio holding.

The recommendation should also include position limits, approved-asset lists, custody controls, counterparty due diligence, liquidity requirements, and periodic risk review. Exposure should be reduced or escalated for human review if market, liquidity, custody, or regulatory risks exceed predefined thresholds.

The objective is not to eliminate potential upside from digital assets, but to ensure that a crypto allocation cannot materially damage the overall portfolio if the asset experiences a severe drawdown.

## 3. T.A.N.G. Social-Engineering Vectors and Bank Defenses

### Vector 1 — Impersonation and Urgent Payment Requests

An attacker may impersonate a senior executive, relationship manager, customer, or trusted counterparty and request an urgent payment or transfer. Social-engineering messages can create pressure by claiming that the transaction is confidential, time-sensitive, or required to prevent a business problem.

**Bank-side defense:** Require independent verification for unusual or high-value transactions. The verification should use a trusted communication channel already registered with the customer rather than replying to the suspicious message. Transactions that materially deviate from the customer's normal behaviour should also trigger additional authentication or human review.

### Vector 2 — Credential Theft Through Phishing

An attacker may send a convincing message that directs an employee or customer to a fake login page. The attacker can then use captured credentials or authentication information to access accounts or initiate fraudulent activity.

**Bank-side defense:** Use phishing-resistant multi-factor authentication where possible, domain and email-security controls, device and session monitoring, transaction-risk scoring, and employee/customer awareness training. Suspicious login behaviour or changes in device, location, or transaction patterns should trigger additional verification.

## Conclusion

Blockchain and crypto-assets can provide new financial opportunities, but they introduce market, liquidity, technology, governance, custody, regulatory, and fraud risks. A bank should therefore treat digital-asset exposure as a controlled risk allocation rather than simply an investment opportunity. Clear exposure limits, independent verification, monitoring, human escalation, and strong cybersecurity controls are necessary to prevent a small digital-asset or social-engineering event from becoming a material financial loss.
"""

with open(
    "ai_advisory_blockchain/blockchain_risk_note.md",
    "w",
    encoding="utf-8"
) as f:
    f.write(blockchain_note)

print("Created: blockchain_risk_note.md")
print("Word count:", len(blockchain_note.split()))

import os

path = "ai_advisory_blockchain/blockchain_risk_note.md"

print(
    "Exists:",
    os.path.exists(path)
)

print(
    "Size:",
    os.path.getsize(path),
    "bytes")

import os

MOCK_LLM = os.getenv("MOCK_LLM", "1") == "1"

def llm_mode():
    if MOCK_LLM:
        return "MOCK_LLM"
    return "REAL_LLM"

return {
    "investor_id": investor_id, ...}

"llm_mode": llm_mode(),

import os

os.environ["MOCK_LLM"] = "1"

from advisory_agent import MOCK_LLM

print("MOCK_LLM enabled:", MOCK_LLM)